### ISSUE TITLE
Response List Page UI Updates

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#1040]
Update the admin [response list page](https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/pages/ResponseList/components/ResponseListForm.js) with the following features:
- Add an email column to the table showing the user's email address, this will also require a small update to the [backend API](https://github.com/deep-learning-indaba/Baobab/blob/706b669850ff9c094cc3ab240d1be273cf5504ec/api/app/responses/api.py#L319) to return the user's email address 
- Add a search box which filters the email or user column in the table, to allow the admin user to easily find someone using their email address or name

**Comment by Malaba6** [comment]
Hi @avishkar58, can I work on this one?
