### ISSUE TITLE
CreateAccount descriptions can be improved

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#105]
At the moment the field descriptions on the CreateAccount form are tooltips, this is not obvious to the user and also not visible on mobile. Rather make these one-liners below each field name (or introduce a clickable info icon to make it obvious that there's a tooltip and workable on mobile)

**Comment by KaleabTessera** [comment]
This has been implemented, but I want to do a bit more work to make it easier to click on mobile.
