### ISSUE TITLE
Homepage Event-list displays "Application not available"

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#106]
After logging in to the test instance, the status column of the event list shows "Application not available" (instead of "Apply Now"). Before logging in, it correctly shows "Apply now"

**Comment by danielamassiceti** [comment]
I have noticed the same after trying the test instance this morning.

**Comment by KaleabTessera** [comment]
Just re-opening this. It seems to work for new users created, but existing users still say application not available. @avishkar58 @danielamassiceti Can you two check for your users?

**Comment by danielamassiceti** [comment]
I had applied & withdrawn (message said Application withdrawn), and have
now applied again. Messages is Applied. Without creating a new user
profile, not sure I can recreate the settings to see if I get the
application not available setting.

**Comment by avishkar58** [comment]
Also can't replicate because I already filled in an application form with the account I crreated.

**Comment by KaleabTessera** [comment]
Created a new user and this works as expected. Closing for now.
