### ISSUE TITLE
Add word counter to TextArea form control

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#108]
We have minimum and maximum word limits on our long-text questions, but no easy way for a user to see how many words they've entered. Add a word counter to the FormTextArea component.

**Comment by arunavkonwar** [comment]
Hi @avishkar58 . I want to take up this issue. Is there a development login credential? I can't seem to verify my account after registering, so that I can check out the forms.

**Comment by avishkar58** [comment]
Hi, there is currently an issue ( #110 ) that the development environment is pointing to the production back-end. As a temporary workaround, please copy the contents of .env.development to .env.production - you will then see the verification email logged to the console and you can use that link to verify your email. (you may also want to merge in #109) 

Thanks for taking up this issue!
