### ISSUE TITLE
Update travel and acommodation grants to work with tags.

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#1099]
## Motivation
At the moment we can only assign travel grants to people who receive offers (ie applied to attend) and not to invited guests. This task will decouple the travel and accomodation grant from offers and make them a lot more generic to allow it to be used for both selected attendees and invited guests and also support other types of grants in the future. 

## Steps
1. Remove travel_award, accommodation_award, accepted_accommodation_award, accepted_travel_award from the offer model (in api/app/registration/models.py)
2. Add a type field to the Tag model (app/app/tags/models.py) (so we can mark certain tags as being of type "grant") 
3. Add a description field to TagTranslation (so we can put details about the grants here)
4. <TODO>

**Comment by avishkar58** [comment]
@danielamassiceti would you be able to work on this one please? The steps still need some more work! Happy to brainstorm it with you.

**Comment by danielamassiceti** [comment]
Hi @avishkar58. After reading your doc and familiarising myself with the various files that will be involved in this PR, I've made an attempt at a set of detailed steps. Let me know if I am on the right track (I've got a few questions here and there), and I will then get started!

Steps:

1. Update Tag and TagTranslation models in tags/model.py
1.1. Add tag type - what options should be permissible here? Only type 'grant' - or should this be 'accomodation_award' and 'travel_award' or others? Also, is the set of types specified only by us, or by admins in general (i.e. should be 'enterable' from the front-end)?
1.2 Add tag description - again, is this captured by admins on the front-end when they add a new tag?
1.3 Create migration to update database with new models

2. Update the Tag API in tags/api.py
2.1 Update _serialize_tag_detail and _serialize_tag to work with the new fields
2.2 Update TagAPI's get, post, and put to work with the new fields
2.3 Update TapListAPI to work with the new fields

3. Shift Tags from Response to Offer and InvitedGuest in back-end
3.1 Remove class ResponseTag in responses/model.py (?)
3.2 Create class OfferTag in offer.model.py (?) -- follow same template as ResponseTag (?)
3.3 Create class InvitedGuestTag in invitedGuest/model.py (?) -- follow same template as ResponseTag (?)
3.4 Create migration to update database with new models

4. Update front-end to work with new tag models
I am not quite sure how the front-end should change. Currently, it seems that you can only add/delete tags from directly within a response (i.e. responsePage). Now that we're broadening it out to offers and invited guests, should we instead have a similar UI appear in each row of the table of invited guests? Or perhaps should we shift the functionality to add/delete tags to a page accessible via an "Add/Specify Tags" (or (Assign Travel Grants?) option in the Event Admin drop-down menu? 
- Files involved: responsePage.js, responseList.js, invitedGuest.js + components? 

5. Clean-up Offer back-end (model and API) and front-end - in api/app/registration/model.py + /api.py
5.1 Remove travel_award, accommodation_award, accepted_accommodation_award, accepted_travel_award from the offer model (registration/models.py) + create migration to update the database with the new model). 
5.2 Remove all award stuff from Offer API. Functions to update: offer_info, update_offer_info, OfferAPI (put, post, get),
5.2 Migrate all data from old events into new format - should this be a separate script that just directly updates the table manually?
5.3 Update Offer front-end (pages/offer/components/OfferComponent.js) remove all UI for travel_award, accommodation_award and accepted versions

6. Clean-up RegistrationSection (model and API) - in api/app/registration/model.py + /api.py
6.1 Remove conditional display stuff for awards in models.py
6.2. Replace with 'show_for_tag' logic in models.py -- needs to work for selected candidates and guests who have corresponding tag
6.3 Update corresponding API -  RegistrationAPI (get), RegistrationSectionAPI (registration_section_info, registration_section_fields, post)

**Comment by avishkar58** [comment]
Hey @danielamassiceti, that looks like a good plan thank you! Some comments/answers to your questions:

1.1. I was thinking the type would be something we control, so enum values defined in the database like "grant" and "response" which help determine where the tags can be used. In fact now that I think about it more, grant is also too specific and we want something that captures a tag which can be used for people who received an offer or are a guest... the common element between those is registration, so perhaps we have "registration" as the new tag type ? 
1.2. Yes the description would be some additional information that an event admin can capture on the front-end when creating a tag. I was thinking for the Indaba we would configure some registration tags like "flight grant" with description "You have been granted a return flight to Accra from an African airport" and "road travel grant" with description "You have been awarded a return bus ticket to and from Accra" etc. 

3.1. We should keep ResponseTag as it is because we'll still use that for tagging responses for review purposes. So I'd say in general keep the existing tag functionality working as it is, but the new features allow tags to be used in more places - ie also in offers and for invited guests. 
3.2 and 3.3 sounds good to me!

4. Yeah good question! Perhaps a tag management page where we can view existing tags and add new tags with their associated type, name and description. WDYT? Then I'd say keep the existing functionality to add tags on the response page and we'd also want some functionality to add tags on the invited guest page. You can also just add tags to the offer POST API since we don't have a UI for creating offers yet. Then we can pass those from the front-end when we make one. (FYI for the Indaba we manually POST offers from Colab, so having tags in the offer POST will still be useful for that so we can specify what grants people receive with their offers) 

5.2.(2) You can do this as part of your migration script that removes the columns from offer table, since these scripts can run any arbitrary SQL statements in them :) 

Some more things to consider:
- In the Offer API is currently we have some logic which sends different emails depending on the combination of travel_award and accommodation_award that is set on the offer. We'd want to replace this logic too to work for tags. I'm actually not entirely sure how this should work. Perhaps we need tags on the email_template table too? Or maybe we just send a standard email for offers and can have separate emails associated with assigning a tag? Let me know if you have a good solution in mind for this, otherwise i'll think some more about how we can do this
- We might also want a new API for assigning tags to offers/guests, so that we can assign tags to a guest after they've had an offer or been invited. This API should also ideally be able to trigger emails to inform people that they received such a grant, so how to do that will depend on the solution to the previous point too I guess!

Thank you!
