### ISSUE TITLE
Dynamic scaling of DLI logo for mobile

### ISSUE THREAD

**Issue by danielamassiceti** [deep-learning-indaba/Baobab#116]
DLI logo (home page and others) does not scale to fit screen size, and hence introduces an unnecessary horizontal scroll bar.

**Comment by jaderabbit** [comment]
Alternatively, this happens and it just gets cut off

![image](https://user-images.githubusercontent.com/5547095/53906557-e631d700-4053-11e9-891c-d07bf158d8d7.png)
