### ISSUE TITLE
Grey/disable questions if "No" selected for Travel Awards and Indaba 2017/2018 attendance

### ISSUE THREAD

**Issue by danielamassiceti** [deep-learning-indaba/Baobab#126]
"Do you want to be considered for a travel award?"
If None, disable/grey out all subsequent text fields.
If Yes, accommodation & transport OR Yes, transport only: (1), (2) and (3) enabled + validation checks 
If Yes, accommodation only, (1) and (3) enabled + validation checks

(1) motivation paragraph (2) departure airport (3) would you still attend

"Did you attend the 2017 or 2018 Indaba"
If No, disable/grey out following text field.
If any of yes options, enforce validation check

**Comment by avishkar58** [comment]
Marking low-priority as it will be a fairly substantial engineering effort.

**Comment by avishkar58** [comment]
This functionality was implemented in the registration form - see there and implement the same logic in the application form.

**Comment by avishkar58** [comment]
Closing this as it is now covered by #601 and #602
