### ISSUE TITLE
Implement email for password reset

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#13]
Implement email functionality in back-end password-reset API - see TODO in api/app/users/api.py

**Comment by jaderabbit** [comment]
@avishkar58 @KaleabTessera 

Any suggestion on mail servers? 
- We could host our own
- We could use sendgrid (but they have a pricetag depending on usage. for the first 90 days its free up to 40 000 emails. Then it's 100 per day for free. If this is to largely be used for communication with all attendees, not idea)
- We could use mandrill (their pricing is WAY more reasonable. works on a credit based system. http://mandrill.com/pricing/ $20 per block - which is 25 000 emails)

**Comment by avishkar58** [comment]
I don't think we should host our own - too easy to get classified as Spam... Mandrill looks good, the block pricing will definitely be more reasonable for us and we already use Mailchimp - will get the Mailchimp account details and sign up for Mandrill

**Comment by nischalhp** [comment]
@avishkar58 once mandrill account details are setup, I will take this task up to send email for password reset.

**Comment by avishkar58** [comment]
Hmm... so hidden costs - you can only use Mandrill if you have a monthly plan with Mailchimp! Argh! Will compare with other options on that basis and feedback...

**Comment by avishkar58** [comment]
Mailgun looks good (https://www.mailgun.com/email-api) - 10000 free emails per month!

**Comment by Carvalho96v2** [comment]
@avishkar58 [Amazon Simple Email Service](https://aws.amazon.com/ses/) seems like a good alternative too. 62k free outgoing emails, and 1k free incoming emails.

**Comment by avishkar58** [comment]
@Carvalho96v2 NICE! Thanks for sending that - we probably won't be hosting in EC2 (because we can most likely get some credits for GCP), so won't get the 62k free emails, but even at "$0.10 for every 1,000 emails you send" - it seems very reasonable! Will set it up asap

**Comment by avishkar58** [comment]
So I've signed up for Amazon SES - we're currently in Sandbox mode, so can only send to verified email addresses. I'll add the emails of everyone in this thread for now - please respond to the verification email you get from Amazon. I'll also email you all the SMTP credentials. 

Docs:
[Python API](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-sdk-python.html), [API Reference](https://docs.aws.amazon.com/ses/latest/APIReference/Welcome.html)

**Comment by nischalhp** [comment]
On it!

**Comment by nischalhp** [comment]
Hello @jaderabbit , @avishkar58 :

Here is the PR for supporting email for password reset : https://github.com/deep-learning-indaba/Baobab/pull/26

If you already have a template for what the email should contain, I will add it in the TODO section of the api, currently have a provided an implementation for sending email via amazon ses.

**Comment by nischalhp** [comment]
@jaderabbit , @avishkar58 - any updates on this? I can fix that as part of some fixes in the PR. What should the password reset mail point to, or should it just say, thank you, your password has been reset and a link to login?

**Comment by avishkar58** [comment]
Yeah I don't think it matters too much - whatever you think is sensible for the email is fine :)

**Comment by nischalhp** [comment]
@jaderabbit - Should I point to any link for resetting password once the user wants to reset their password?

**Comment by jaderabbit** [comment]
@nischalhp I don't know if we have an actual front-end yet. @KaleabTessera ? 
You'll need to email them a token and then setup the end points for resetting

**Comment by nischalhp** [comment]
@KaleabTessera - Yes, that sounds good. So when a user resets his password, he gets an email with the above mentioned url, that he can later use to reset it. 
Also the reset token, it needs to be generated and added to database? @jaderabbit
