### ISSUE TITLE
Airport codes

### ISSUE THREAD

**Issue by shakirm** [deep-learning-indaba/Baobab#133]
Is is possible to provide a list of codes (like we have for the countries boxes), to show the list of all airports (and IATA codes). Perhaps using the list from here: https://en.wikipedia.org/wiki/List_of_airports_by_IATA_code:_A Haven't found a better list online yet.

**Comment by NileshArnaiya** [comment]
I'm not sure where to place the Select Input
![Screenshot from 2020-01-24 19-53-05](https://user-images.githubusercontent.com/10388565/73076695-9dda0c80-3ee4-11ea-9296-a1e56a5eea6a.png)
I put it below Country of Nationality
Is this fine?

**Comment by avishkar58** [comment]
Hey @NileshArnaiya ,

Sorry for the lack of details on this issue. We don't want to capture departure airports as part of the user profile. In fact, we're removing most of the fields from user profile (see #439 ). Departure airport was a question on the application form though, and the options on that form are all configurable in the database (see app/applicationForm/models.py) so there's actually no development work to be done here. 

Will try go through the older issues and update them if they're still relevant. In the meantime perhaps it's better to start on one of the newer issues?

We can keep this issue open as a reminder when configuring the form this year, but I'd say rather park this for now. 

Thanks for jumping in to help us! :)

**Comment by NileshArnaiya** [comment]
Sure, No Problems. I'll go through the newer issues :)

**Comment by avishkar58** [comment]
Closing, will configure this in options for this year's application form.
