### ISSUE TITLE
Quality of logo

### ISSUE THREAD

**Issue by shakirm** [deep-learning-indaba/Baobab#137]
Logo quality is not good on a computer. Let me know what is needed to improve its rendering. I'll send over an SVG, PDF and PNG that might be better. Also assess this change on speed of loading and rendering on mobile.

**Comment by avishkar58** [comment]
Hey Shakir, do you mean the logo in the menu bar or the one on the homepage? If you have a high quality PNG in mind, please do send that. Thanks!
