### ISSUE TITLE
Add fields to Create Account form

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#14]
Add the additional fields found in the User table of the [Application Process Spec](https://docs.google.com/document/d/1173JsQzl0KnjtLZ4bE5PK2j_YDTJF55ssoR9I19tQGs) to the front-end CreateAccount page. This depends on #11 being completed before this will work end-to-end.

**Definition of Done**
This task is done when: 
* The CreateAccount component has been updated with the additional fields found in the application process spec
* The fields are visible in the CreateAccount page
* The service calls have been updated and correctly pass the full set of fields to the back-end API
* A manual integration test has been performed as the functionality is working as expected.

**Comment by avishkar58** [comment]
Hey Kale-ab, are you still working on this one? Busy with issue #10 and can do this one now quickly if you haven't started yet?

**Comment by KaleabTessera** [comment]
Hey Avishkar, yes I am quite far with this one. I quickly stopped this, to get the Continuous Integration working.

I am doing a bit of rework on how this form works so i think it would be easier if I finish it. :)

**Comment by avishkar58** [comment]
Ok awesome :) thanks!

**Comment by KaleabTessera** [comment]
Closing for now, will create new tickets for bugs etc.
