### ISSUE TITLE
CORS failed on application submission

### ISSUE THREAD

**Issue by jaderabbit** [deep-learning-indaba/Baobab#144]
For some reason, when accessing from the `test-baobab` website, CORS failed when I submitted

**Comment by avishkar58** [comment]
Hey @jaderabbit , did this stop you from submitting? I don't seem to be getting any CORS issue when submitting...

**Comment by jaderabbit** [comment]
It did. It was very strange. I'll try replicate

**Comment by avishkar58** [comment]
No further reports of this, closing.
