### ISSUE TITLE
Fix user experience after application is submitted

### ISSUE THREAD

**Issue by jaderabbit** [deep-learning-indaba/Baobab#146]
After application submitted, an edit button (available if before deadline date) next to the withdraw button would be useful

![image](https://user-images.githubusercontent.com/5547095/54077738-64e17b00-42c5-11e9-9113-fbcc6e431d07.png)

Then on front page, one application is submitted, next to status, links to "withdraw" and "edit" might be very useful (if before deadline)
![image](https://user-images.githubusercontent.com/5547095/54077714-23e96680-42c5-11e9-8ed4-114753ce7410.png)

**Comment by Carvalho96v2** [comment]
Sorry for the hiatus, I can take this.
