### ISSUE TITLE
Re-verify email if user changes it

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#147]
Users are able to update their email address on the profile page, if they do so, we should re-validate their new email address.

**Comment by DonneStevenson** [comment]
@jaderabbit I assigned this ticket to myself then saw had already created a branch for this ticket, are you currently working on it?

**Comment by jaderabbit** [comment]
Not currently. I can't remember if i did it or not :/ I feel like I might have.

**Comment by DonneStevenson** [comment]
I saw there weren't any commits so I finished the ticket in the meantime, hope that was okay?
