### ISSUE TITLE
Add flask-admin for basic CRUD

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#151]
Restrict access to admin users. 

See https://flask-admin.readthedocs.io/en/latest/ 
and https://github.com/flask-admin/flask-admin/tree/master/examples/sqla

**Comment by jaderabbit** [comment]
@avishkar58 I've actually done this. I just need to figure out the security

**Comment by avishkar58** [comment]
Hey Jade, just checking how this is going? I'm wondering if I should create issues to implement "add user role" functionality or if we can do this with flask-admin

**Comment by jaderabbit** [comment]
No. I'm terrible. I haven't worked on it since. It's not hard. How urgent is the user role? Because I'll be able to get to it this weekend and we can do it then. 

Alternatively, I pushed the 2 lines it took to make the admin dashboard if that might be easier to finish? 
`feature/admin`
