### ISSUE TITLE
Country of Nationality/Residence are drop downs with no options

### ISSUE THREAD

**Issue by greg-newman** [deep-learning-indaba/Baobab#157]

**Comment by KaleabTessera** [comment]
Hi Greg,
What environment/url?

**Comment by avishkar58** [comment]
Hey @greg-newman , can you also specify which browser you are using and whether you see any Javascript (or other) errors in the console?

**Comment by greg-newman** [comment]
Nvm, I hadn't run the migrations while testing the logging locally. Nothing to see here.
