### ISSUE TITLE
Add Date of Birth and Primary Language to user profile

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#160]
Add date of birth (date selector) and primary language (free text) to the user profile. This involves: 

1. Update the AppUser model to add these fields
2. Create a migration to apply the changes to the database
3. Update the User controller if necessary (probably not necessary) 
4. Update the createAccount and userProfile front-ends to capture the new fields.

**Comment by avishkar58** [comment]
Hey @KaleabTessera - can you do #162 while doing this one?

**Comment by KaleabTessera** [comment]
Cool, will do @avishkar58
