### ISSUE TITLE
Add a "report a bug" button

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#161]
Add a "report a bug" button that is just a mailto:baobab@deeplearningindaba.com link to the front-end. I'm thinking this can go in the footer on the right (so in the bottom right corner of every page)

**Comment by KaleabTessera** [comment]
We should also have this on our Error page. Right now we ask them to email us, it would be nice if there was a link there (maybe even pre-populate the Subject of the email).
