### ISSUE TITLE
Create Event Data model

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#17]
Create the datamodel for Event and EventRole (using SQLAlchemy ORM), as per the [applications process spec](https://docs.google.com/document/d/1173JsQzl0KnjtLZ4bE5PK2j_YDTJF55ssoR9I19tQGs/edit?ts=5c3c5fec).

Pre-populate the event table with the following event:
**name**: Indaba 2019
**description**: The Deep Learning Indaba 2019, Kenyatta University, Nairobi, Kenya
**startDate**: 25 August 2019
**endDate**: 31 August 2019

**Definition of Done**
This task is done when

* The relevant models exist in api/app/event/models.py
* A new migration exists that creates the necessary tables in the database
* Data is added as part of the migration
* The migration can be applied successfully
* Unit tests are optional for this task

**Comment by Carvalho96v2** [comment]
I can run with this issue, and seeing as they're closely related, I can take issue #18  too if that's cool

**Comment by Carvalho96v2** [comment]
Hey @jaderabbit, I'm having trouble creating migrations, could you please assist?

I created a bash shell within the baobab_web_1 container using:
`docker exec -it baobab_web_1 /bin/bash`

And from there I tried creating a new migration revision with:
`flask db migrate`

Unfortunately, I'm consistently greeted with the following error message:
`Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.`

**Comment by avishkar58** [comment]
Maybe try ```python ./api/run.py db migrate``` instead?

**Comment by jaderabbit** [comment]
@Carvalho96v2 
`docker-compose run web python ./api/run.py db migrate --directory api/migrations` to generate a new migration
`docker-compose run web python ./api/run.py db upgrade --directory api/migrations` to run them

**Comment by Carvalho96v2** [comment]
@jaderabbit Sorry, must've missed that in the readme. That worked, thanks so much.

**Comment by jaderabbit** [comment]
@Carvalho96v2 Yay! Glad to hear it ^_^
