### ISSUE TITLE
Populate Review Form

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#175]
Create a migration that populates seed data in the ReviewForm and ReviewQuestion tables. The data required is as follows:

- A review form for the current ApplicationForm that exists in the DB (with id 1), which is open and has a deadline set to "10 May 2019"
The ReviewForm should have the following ReviewQuestions (in this order):

- Headline: "Encourage field of study?"; description: "Is the applicant from a field of study we want to encourage? ie outside of CS/Maths/Stats?"; type="checkbox"; 

- Link to "Why is attending the Deep Learning Indaba 2019 important to you?"; type="multi-choice"; options=Poor: 0, Below Average: 1, Average: 2, Above Average: 3, Excellent: 4; is_required: true;

- Link to "How will you share what you have learnt after the Indaba?"; type="multi-choice"; options=Poor: 0, Below Average: 1, Average: 2, Above Average: 3, Excellent: 4; is_required: true;

- Link to "Share with us a favourite machine learning resource you use: a paper, blog post, algorithm, result, or finding. Tell us why."; type="multi-choice"; options=Poor: 0, Below Average: 1, Average: 2, Above Average: 3, Excellent: 4; is_required: true;

- Link to "Are you or have you been a tutor for any relevant course, or part of any machine learning or data science society or meetup? If yes, give details."; description: "Based on this answer, do you believe the applicant has been a tutor for a relevant course?"; type="multi-choice"; options=Poor: 0, Below Average: 1, Average: 2, Above Average: 3, Excellent: 4; is_required: true;

- Link to "Have you worked on a project that uses machine learning? If yes, give a short description."; type="multi-choice"; options=Poor: 0, Below Average: 1, Average: 2, Above Average: 3, Excellent: 4; is_required: true;

- Link to "Did you attend the 2017 or 2018 Indaba"; type="information"; 

- Link to "If you attended a previous Indaba, tell us how it has helped you grow or how you have used what you have learnt." type="multi-choice"; options=Poor: 0, Below Average: 1, Average: 2, Above Average: 3, Excellent: 4; is_required: false;

- Link to "Would you like to be considered for a travel award?"; type="information"

- Link to "If you do not receive a travel award from us, will you still be able to attend?"; type="information"

- Link to "If you selected yes, please provide a short motivation for why you should be considered for a travel award."; type="multi-choice"; options=Poor: 0, Below Average: 1, Average: 2, Above Average: 3, Excellent: 4; is_required: false;

- Link to "Any additional comments or remarks for the selection committee?"; type="information"

- Link to "Anything else you think relevant, for example links to personal webpage, papers, GitHub/code repositories, community and outreach activities."; type="information"

- Headline: "Final Verdict"; description: "Do you think this applicant should attend the Indaba?"; type="multi-choice"; options=No: 0, Maybe: 1, Yes: 2; is_required: true

(set weights to 0 on all the ReviewQuestions for now, as these have not been finalized yet)

**Comment by avishkar58** [comment]
Hey @amritpurshotam , not sure how far along you are with this, but please note that we decided to change the "Have you been a tutor" ratings to a scale, instead of a "yes or no" - thanks!

**Comment by amritpurshotam** [comment]
@avishkar58 The tests on the other review controller ticket are taking a bit longer than I expected (so many scenarios) but I'm almost done. I should get to this one by tonight

**Comment by avishkar58** [comment]
@amritpurshotam cool, thanks. Really really appreciate all your hard work on Baobab!! :)

**Comment by amritpurshotam** [comment]
@avishkar58 For the question (Is the applicant from a field of study we want to encourage? ie outside of CS/Maths/Stats?), is it required? Just asking because it does sound like it could be

**Comment by avishkar58** [comment]
Well it's not required in the sense that if the reviewer doesn't check the checkbox we just assume the value is 0... so the front-end doesn't require any action from the user is what I meant by not required.

**Comment by amritpurshotam** [comment]
@avishkar58 Ah of course, that makes sense. 

In that case though, (I don't feel particularly strongly about this so going with either is fine) something I do prefer is for a user to make an explicit decision to say yes or no with a radio button control that has both options unselected initially. With a checkbox, you can't really differentiate between someone saying no or just forgetting to answer the question.
