### ISSUE TITLE
Redirect user to login if auth fails

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#180]
Authorization might fail due to an expired token, in which case the API will return a 401 status code. At the moment, many of our pages will just display an error to the user if  this happens. Instead, we should redirect the user to the login page.  Create some common functionality in the front-end services (eg in base.service.js) to implement this.

**Comment by KaleabTessera** [comment]
@avishkar58 
So I have implemented and tested this and it intercepts errors with a 401 and redirects to login as expected.

However, there are other errors which return a 401, for example: 
- EMAIL_VERIFY_CODE_NOT_VALID
- RESET_PASSWORD_CODE_NOT_VALID
- BAD_CREDENTIALS

I am assuming we only want this behaviour for UNAUTHORIZED errors?

In this case I will change the error codes returned for the other errors.

**Comment by avishkar58** [comment]
Thanks! Yeah we definitely only want this for genuine unauthorized errors
:)

**Comment by KaleabTessera** [comment]
Closed by https://github.com/deep-learning-indaba/Baobab/pull/195.
