### ISSUE TITLE
Implement ReviewForm controller

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#181]
Create a ReviewForm controller with a GET method that accepts an "event_id" and "skip" parameter. The method should do the following:
- Get the review form for the event
- Determine which reviews are yet to be completed for the logged-in user (reviewer), by querying the ResponseReviewer and ReviewResponse tables
- Optionally Skip some reviews based on the skip parameter to determine the current review (the skip should be maxed at the number of reviews available) 
- Get the AppUser, Response and Answers related to the current review 

The method should return the following:
- The ReviewForm for the event
- List of ReviewQuestions for the ReviewForm
- The Answer value for each ReviewQuestion if applicable (remember to resolve the label in the case of a "multi-choice" question) 
- The following fields from the AppUser being reviewed: Country of Nationality, Country of Residence, Affiliation, Department, User Category   (don't return any other fields!) 

- Return an appropriate status code (eg 404?) if there are no more reviews left. 

**Definition of Done**
- New ReviewForm controller has been created in api/app/reviews/api.py
- Tests exist for the functionalitiy

**Comment by amritpurshotam** [comment]
> The Answer value for each ReviewQuestion if applicable (remember to resolve the label in the case of a "multi-choice" question)

@avishkar58 Just going through this ticket again. I'm unsure what you mean by resolving the label. I don't think I did this. I'm just showing the `value` field.

**Comment by avishkar58** [comment]
Hey @amritpurshotam 
If you link to a question like "Did you attend a previous Indaba", the value in the answer table will be something like "indaba-2017", but in the question table, the options field has something like: 
[
{label: "Yes I attended the 2017 Indaba", value: "indaba-2017"},
{label: Yes, I attended both Indabas", value: "indaba-2017-2018"},
]

So in this case we would like to map the value to the label and have "Yes I attended the 2017 Indaba" returned instead of the "indaba-2017" 

Hope this makes sense?

**Comment by amritpurshotam** [comment]
@avishkar58 Sorry I missed this and we've already merged the branch but I can make a new one for this.

I think I understand. How will I know how to identify these kinds of questions? Or do you want to specifically handle this question?

And is this what you want the response (i took out the fields that don't matter for this example)?

```
{
    "response": {
        "answers": [
            {
                "id": 1,
                "question": "Did you attend a previous Indaba?",
                "question_id": 1,
                "value": "Yes, I attended both Indabas"
            }
        ]
    },
    "review_form": {}
    "reviews_remaining_count": 1,
    "user": {}
}
```

**Comment by avishkar58** [comment]
Sorry for the late response. These can be identified by the Question having type "multi-choice" - here's some code where something similar in the response controller: 

```
def _get_answer_value(answer, question):
    if question.type == 'multi-choice' and question.options is not None:
        value = [o for o in question.options if o['value'] == answer.value]
        if not value:
            return answer.value
        return value[0]['label']
    
    if question.type == 'file' and answer.value:
        return 'Uploaded File'

    return answer.value
```

Yes, your example is exactly what the response should look like :)

**Comment by amritpurshotam** [comment]
@avishkar58 Thanks for code. Will implement now.
