### ISSUE TITLE
Incorrect Unique Constraints on Section table

### ISSUE THREAD

**Issue by amritpurshotam** [deep-learning-indaba/Baobab#191]
Is there a reason that there are two unique constraints on the `Section` table on the `name` and `order` columns? This means that when setting up the sections for a new form (after one already exists) you will not be able to reuse sections with the same name and your ordering will have to start from the max + 1 of the previous form. 

A single unique constraint on the application_form_id, name, and order columns would make sense though (even this could be argued is a bit excessive). 

What does everyone else think?

**Comment by avishkar58** [comment]
Yes that constraint doesn't make sense... It should include application
form id or be removed

Thanks!

**Comment by amritpurshotam** [comment]
@avishkar58 Okay sure will remove the constraint. This is a table that will only be updated by an admin so don't think we need to be too strict with the constraints.

**Comment by amritpurshotam** [comment]
Also picked this up while setting up test cases for the reviews. I set up multiple events to make sure that filter was working properly
