### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#23]
Implement a user profile page that allows a user to update their user details. This should leverage the components built in #14 and make the relevant API call using the userService. 

**Definition of Done**
This task is done when:
* A user profile page has been created, leveraging the CreateAccount components
* The userService has been updated to make the relevant API call (if not done already) 
* The user profile is accessible from the "logged in user" menu on the navbar (built in issue #10 )
* A basic unit test has been added to check that the page renders
* A manual integration test confirms that user accounts can be updated.

**Comment by hbarnardt** [comment]
@KaleabTessera Are you working on this issue?

**Comment by KaleabTessera** [comment]
@hbarnardt Haven't had a chance to start on this. You can def take this one on. I will un-assign myself.

**Comment by hbarnardt** [comment]
This will also implement the front end for #22
