### ISSUE TITLE
Create account doesn't allow special characters 

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#238]
If someone has non-ASCII characters in any of the fields (like ö,ü,ä), they get this error: 

https://reactjs.org/docs/error-decoder.html/?invariant=31&args%5b%5d=object%20with%20keys%20%7Baffiliation%7D&args

**Comment by avishkar58** [comment]
Hey @KaleabTessera are you still working on this? I think you already did something to fix this for the invitation letters right?

**Comment by KaleabTessera** [comment]
Yeah, I will just test this out for create account before closing. Also python3 will probably affect this, this prev method was needed for python2.

**Comment by KaleabTessera** [comment]
Done.
