### ISSUE TITLE
wsgiref in the api requirements supported by python  < 3.2

### ISSUE THREAD

**Issue by nischalhp** [deep-learning-indaba/Baobab#25]
Hello Team,

The wsgiref in the api requirements is not supported for python 3.6 : https://pypi.org/project/wsgiref/0.1.2/, the Amazon SES has been tested on python 3.6 and 2.7 : https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-sdk-python.html.

Should we take a look at this library?

**Comment by avishkar58** [comment]
Hey Nischal, not sure I follow exactly? Do you want to move to Python 3.6 to support the Amazon SES library? In that case we don't need wsgiref..?

**Comment by nischalhp** [comment]
Hello @avishkar58 ,

No not really, just concerned that wsgiref does not support 3.6. The mail protocol to support Amazon SES should not have a problem with 3.2 but just wanted to be sure that everyone is aware that we cannot support the system with any python version greater than 3.2 because of this dependency.
