### ISSUE TITLE
Create Invited Guest back-end

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#266]
We need to capture invited guests for an event in Baobab. An invited guest may be a speaker, organiser, friend-of-the-Indaba, mentor etc. 

Many invited guests will already have Baobab accounts, but it is not reasonable to expect every invited guest (eg. high profile speakers) to create an account. 

TASK:

1. Create an InvitedGuest model (in api/app/events or create a new folder, as you think is appropriate):
The model should contain the following:
- id (int, primary key, required)
- event_id (ref event table, required)
- user_id (ref app_user table, required)
- role (string, required)

2. Create an InvitedGuest controller
- Implement a POST method - the method should accept an email address, event_id and role. First check if there is a Baobab user account associated with the email address, if not return a 404 error, then add the entries to the invited_guest table. 

3. Create a CreateUser controller with a POST method that accepts all the required details to create a new entry in the app_user table (see the User controller), except for password. This should create a new entry in the app_user table with a random password but NOT send any email to validate the user (ideally re-use as much functionality in the user controller as possible) 

4. Create an InvitedGuestList controller with a GET method that accepts an event_id as a parameter and returns the list of invited guests for that event.

**Comment by KaleabTessera** [comment]
@avishkar58 Will the guest ever need the random password (according to point 3)? Is this just a way around having a required password for an app_user?

**Comment by avishkar58** [comment]
Yeah this is just a way to get around the required password. If they want
to use their account in future they can just use the password reset :)

**Comment by KaleabTessera** [comment]
Closed by https://github.com/deep-learning-indaba/Baobab/pull/269.
