### ISSUE TITLE
Create Invited Guest Front-end

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#268]
Depends on #266 

Create a front-end for the invited guest functionality, that interacts with the backend API created in #266. Specifically, the front-end should display a list of invited guests for the default event, as obtained from the InvitedGuestList controller's GET method.
 
Below the list should be a form accepting an email address and a role (lets add some roles in a drop-down, like "Speaker", "Guest", "Mentor", "Friend of the Indaba", "Organiser"). These should be submitted to the POST method of the InvitedGuest controller. 

If the response is success, reload the table to have the details of the new invited guest added. If the response from the InvitedGuest controller is 404, proceed to a new form that contains the email and role pre-filled, and asks for the rest of the details required to create an app_user account, using the POST method of the CreateUser controller. After doing this, re-send the POST to the InvitedGuest controller to add the new user as an invited guest.

**Comment by KaleabTessera** [comment]
@ilzeLourens  Let me know if you need any assistance. 

How to get started:

1. Create an InvitedGuest
- If you have created an AppUser:
`'/api/v1/invitedGuest'` 
- No AppUser -> create an AppUser, then create InvitedGuest
`/api/v1/invitedGuest/create`
`/api/v1/invitedGuest`

2. Call Invited Guest List
`/api/v1/invitedGuestList`
