### ISSUE TITLE
Restart of Docker required to run docker-compose up

### ISSUE THREAD

**Issue by amritpurshotam** [deep-learning-indaba/Baobab#27]
After successfully following steps 1-5 in the Getting Started (Detailed) instructions, on step 6 I got the following error after running `docker-compose up`

    Starting baobab_redis_1  ... error
    Starting baobab_db_1    ...
    Starting baobab_webapp_1 ...

    ERROR: for baobab_redis_1  Cannot start service redis: b'driver failed programming external 
    connectivity on endpoint baoStarting baobab_db_1     ... error
    rt/tcp:0.0.0.0:6379:tcp:172.17.0.2:6379: input/output error'

    ERROR: for baobab_db_1  Cannot start service db: b'driver failed programming external connectivity 
    on endpoint baobab_db_1 (f53ddbbdaf68bc30d741e576f3b33b9505119b74af8cc1447d2a37cd3d9eaecf): Error 
    starting userland proxy: mkdir /port/tcp:0.Starting baobab_webapp_1 ... error

    ERROR: for baobab_webapp_1  Cannot start service webapp: b'driver failed programming external 
    connectivity on endpoint baobab_webapp_1 
    (4e1626d5f44561103ef7c02013b1dc3885a48ae5a37741d4bc67572fbe8dc489): Error starting userland proxy: 
    mkdir /port/tcp:0.0.0.0:8080:tcp:172.17.0.4:80: input/output error'

    ERROR: for redis  Cannot start service redis: b'driver failed programming external connectivity on 
    endpoint baobab_redis_1 (ecbfdfff3fa576ce4259ecfb2268b1ba91a89ca0d4db2a68f15a0237f4ecf1a4): Error 
    starting userland proxy: mkdir /port/tcp:0.0.0.0:6379:tcp:172.17.0.2:6379: input/output error'

    ERROR: for db  Cannot start service db: b'driver failed programming external connectivity on 
    endpoint baobab_db_1 (f53ddbbdaf68bc30d741e576f3b33b9505119b74af8cc1447d2a37cd3d9eaecf): Error 
    starting userland proxy: mkdir /port/tcp:0.0.0.0:5432:tcp:172.17.0.3:5432: input/output error'

    ERROR: for webapp  Cannot start service webapp: b'driver failed programming external connectivity 
    on endpoint baobab_webapp_1 (4e1626d5f44561103ef7c02013b1dc3885a48ae5a37741d4bc67572fbe8dc489): 
    Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8080:tcp:172.17.0.4:80: input/output error'
    ERROR: Encountered errors while bringing up the project.

To fix this (from this link https://github.com/docker/for-win/issues/2722), I had to shutdown Docker and restart it. The `docker-compose up` command would then run successfully. I'm posting this here since I think this is more of a work around than a permanent solution but may still be helpful if anyone else is running into the problem for now. I will continue to look into this for a more permanent solution.

My environment is Windows 10 Pro Build 17134 and I'm running Docker Engine 18.09.1

**Comment by jaderabbit** [comment]
This issue seems to have a long history: https://github.com/docker/for-win/issues/573
Maybe add something to the readme for windows users?

**Comment by avishkar58** [comment]
Added to troubleshooting section on main README
