### ISSUE TITLE
Create User Profile Page

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#287]
Depends on #263 

Create a new user profile page that displays profile information for a single user. 

This page should be accessed by clicking on the user's name in the table in the User Profile list page. Send a GET request to the [User Profile controller](https://github.com/deep-learning-indaba/Baobab/blob/183eadba44476a7d8e566ef45c74989e5fc00e13/api/app/users/api.py#L326) and display all the [fields that are returned by that controller](https://github.com/deep-learning-indaba/Baobab/blob/183eadba44476a7d8e566ef45c74989e5fc00e13/api/app/users/api.py#L261). 

See [here](https://github.com/deep-learning-indaba/Baobab/blob/183eadba44476a7d8e566ef45c74989e5fc00e13/webapp/src/App.js#L281) and [here](https://github.com/deep-learning-indaba/Baobab/blob/183eadba44476a7d8e566ef45c74989e5fc00e13/webapp/src/pages/review/components/ReviewForm.js#L202) for an example of how to create a route that accepts a parameter

**Comment by mthembbu** [comment]
On it. 👍
