### ISSUE TITLE
Create Offer Front-end

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#289]
Depends on #276

Create a page for a candidate to see their offer, accessible at the "/offer" relative URL. 

The page should query the offer controller (from #276) with a GET request.

If no offer was found (404 status code), display a message saying "You are currently on the waiting list for the Deep Learning Indaba 2019. Please await further communication"

If an offer was found, display a message along the lines of:

"We are pleased to offer you a place at the Deep Learning Indaba 2019. Please see the details of this offer below:" 

Display some text along the lines of "You have been accepted as a <USER_CATEGORY>" 
Display the status of the travel award, accommodation award and payment required from the offer

Display the message:
"Please accept or reject this offer by <OFFER_EXPIRY>. 

If you choose to reject this offer, please enter a reason - we will read all of these messages and may be able to help by changing the terms of you offer in a subsequent round of acceptances. If you don't accept or reject by <OFFER_EXPIRY> we will automatically allocate your spot to someone else"

Then present an Accept and Reject button.
If the user clicks on the Reject button, open a textarea prompting them for their reason.
Send the acceptance or rejection + reason to the Offer controller in a PUT request

**Comment by jaderabbit** [comment]
@LindanyRetroRabbit We need this one in today! So, if you need help, pull in one of the others to assist :)

**Comment by jaderabbit** [comment]
@avishkar58 
What happens after it's denied? 

Should we display "An offer with the following details was rejected. If this was a mistake, please contact baobab@deeplearningindaba.com"

**Comment by avishkar58** [comment]
Yeah that sounds good. Maybe add the timestamp too
