### ISSUE TITLE
As an invited guest, my country defaults to Afghanistan according to user profile list interface

### ISSUE THREAD

**Issue by jaderabbit** [deep-learning-indaba/Baobab#300]
![image](https://user-images.githubusercontent.com/5547095/59333657-1c3cc200-8cf9-11e9-9d62-9e8d7c0147ae.png)

Not sure what correct behaviour is here because we don't capture it. Is it defaulting to something we don't have @mthembbu ?

**Comment by mthembbu** [comment]
Hi Jade. I didn't find a way to reproduce the bug issue you raised. (locally) I created new set of users, invited them as guests, and previewed the profile list, and the results did not reflect as per issue. But, will further investigate, once my cards done

**Comment by avishkar58** [comment]
There were a few changes to invited guest since this issue was raised -
please close if it's no longer reproducible.
