### ISSUE TITLE
Update Offer to cater for partial acceptances

### ISSUE THREAD

**Issue by jaderabbit** [deep-learning-indaba/Baobab#304]
**User story**

As a user, I might want to accept the invite to the indaba, but deny the accommodation (perhaps because I prefer booking my own and don't want to share a room). 

As a user, I might want to accept the invite to the Indaba, but deny the need for travel because it turns out I'm in Nairobi then anyways. 

**Proposed fix**
*Model*
Add 2 additional fields to Offer:
- accepted_travel (bool) 
- accepted_accommodation (bool)

*Back-end*
- Adapt the Offer controller to retrieve & update both of those fields

*Front-end*
if awarded_accommodation=True: then 
- display a check box that is by default checked that says "I accept the award of accommodation"

if awarded_travel=True: then
- display a check box that is by default checked that says "I accept the award of travel"

These new fields get saved when model is accepted. 

@avishkar58 This one making sense?

**Comment by avishkar58** [comment]
Makes perfect sense to me :)
