### ISSUE TITLE
Update Baobab front-page to take user to offer, if one exists

### ISSUE THREAD

**Issue by jaderabbit** [deep-learning-indaba/Baobab#305]
Right now, even though I've got an offer waiting for me, the front-page still says this: 

![image](https://user-images.githubusercontent.com/5547095/59384860-783c3080-8d63-11e9-97f3-b6c5b7e6862b.png)

Perhaps it should say, if there exists an offer for the user:

*There is an offer waiting for you, click here to view it*

And the default message should be updated to:

*You are currently on the waiting list for the Deep Learning Indaba 2019. Please await further communication*

@avishkar58  Do we eventually send people rejection emails after a certain date? Maybe we should mention this date somewhere?

**Comment by avishkar58** [comment]
@jaderabbit Yeah I think we should send people rejection emails, especially those who are not based in Nairobi (who we might call on at very short notice to fill last minute places) - will report back with some more details.
