### ISSUE TITLE
User Profile: Sorting by full-name doesn't work

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#320]
Clicking on the "Full Name" title in the table on the user profile list appears to do some kind of random sorting or nothing. It should instead do something sensible like sort by last name.

**Comment by mthembbu** [comment]
@avishkar58 , do you ca if Fullname displays as [firstname lastname, title] ?

**Comment by avishkar58** [comment]
That's fine - we can even make it [Lastname, Firstname] and drop the title
if that makes it easier to sort by lastname?

**Comment by mthembbu** [comment]
like this?
![image](https://user-images.githubusercontent.com/46743536/59858249-e80d7500-937a-11e9-8c90-fff7a74551ac.png)

**Comment by mthembbu** [comment]
Then remove title?

**Comment by avishkar58** [comment]
Yeah that looks fine - I assume this was done to allow sorting to work
properly? Is there no custom sort function hook in react-table that would
allow us to keep the names [title firstname lastname] and still sort by
lastname?

**Comment by mthembbu** [comment]
I spent the whole day trying to add a custom implementation of defaultSortMethod, where the id: firstname, somehow it didn't take effect. I am considering to add onClick on Full-Name, and sort the List outside of the <ReactTable>, then call my sorting onClick, then constantly changing Desc_Asc variable to sort the list in Ascending or Descending order

**Comment by mthembbu** [comment]
In the mean time can I commit this work?

**Comment by avishkar58** [comment]
Sure, if the custom version is complicated then go ahead and commit this
one for now - thanks! :)

**Comment by mthembbu** [comment]
Kindly advise if I can close the card for now?
