### ISSUE TITLE
Registration for InvitedGuests

### ISSUE THREAD

**Issue by KaleabTessera** [deep-learning-indaba/Baobab#323]
Provide registration functionality for invited guests so that they can register to attend the indaba. 

- Invited Guests do not have an offer and all get to register
- Other than that, the registration form is similar.

**Comment by ilzeLourens** [comment]
Hello,
just a few question.
*  Do invited guests log into the site and have their own views?
*  Will the invited guest be filling in the registration form them selves or the admin for them
*  Should  I create a migration with a guestRegistration table, mostly identical to the Registration table just excluding the offer_id and maybe replace it with user_id
* Do the invited guests sit in the same table as appUser

**Comment by jaderabbit** [comment]
Hi Ilze,

- I believe so yes
- "Will the invited guest be filling in the registration form them selves or the admin for them" ~ That is a good question! I think so? @avishkar58 ?
- yes 
- They are in app_user but they have an additional table called `invited_guests` which points to the app_user table

@KaleabTessera @avishkar58

**Comment by avishkar58** [comment]
Agree with @jaderabbit responses - regarding your excellent 2nd question - I think we can assume that invited guests will fill in their own registration forms for now, I imagine some of our speakers won't do that, but that's OK for now

Thanks!

**Comment by ilzeLourens** [comment]
How do we differentiate on the front end if a user is an invited guest,
can we see if the invited_guests column is not null then show a different view accordingly
@avishkar58

**Comment by ilzeLourens** [comment]
f10b76144590dc85a19f05cd809b291404f971b6
I created an end point to see if a user is an invited guest

**Comment by avishkar58** [comment]
Sure that sounds reasonable!
