### ISSUE TITLE
Invitation Letter Generator

### ISSUE THREAD

**Issue by jaderabbit** [deep-learning-indaba/Baobab#328]
This module needs to generate Invitation Letters for a particular user, as per the [Registration spec](https://docs.google.com/document/d/1dBTfmsBvWtCEw36mKYIgRsvMxE0BhMT-mU9iHVcWTrs/edit#)

Create a `api/app/invitationletter/generator.py` module with a `generate` method that takes the following inputs:

- template_path
- event_id 
- work_address
- addressed_to
- residential address
- passport_name
- passport_no
- passport_issued_by
- invitation_letter_sent_at
- to_date
- from_date  
- country_of_residence 
- nationality
- date_of_birth 
- email

It must do the following: 
1. Fetch the word template from google cloud storage. [Here](https://docs.google.com/document/d/1OA-ER_Oscb_P3YETj_rfpql6Txiqg1cYCa0QbB01ZX0/edit?usp=sharing) is an example of a template

2. Replace the tags in the invitation template, with the correct fields . You can use the following package: https://pypi.org/project/docx-mailmerge/ 

3. Convert the word doc to a PDF

4. Email the the user the newly generated invitation letter

5. Return true if email was successful

**Definition of Done**
This task is done when:

- A new module exists in api/app/invitationletter/generator.py implementing method described above 
- Unit tests exist for the module

**Comment by jaderabbit** [comment]
@avishkar58 @KaleabTessera Can you do a sense check here plz

**Comment by avishkar58** [comment]
Looks good to me! Only thing I'd add is that the letter should be converted/saved as PDF before emailing it.

**Comment by avishkar58** [comment]
Note: Please also add whether or not the person is presenting a poster to the fields.

**Comment by jaderabbit** [comment]
> Note: Please also add whether or not the person is presenting a poster to the fields.

Does this need to go on the invitation letter? :P

**Comment by avishkar58** [comment]
Yes, apparently this is useful for people using the letter to seek funding
from their university or company etc :)

**Comment by jaderabbit** [comment]
I figure, we could just have %BRINGING_POSTER% on the templates, and then mailmerge that with text if they're bringing one. I'm trying to avoid another permutation of invitation templates :P

**Comment by avishkar58** [comment]
Yes definitely, much better than doubling the templates :)
