### ISSUE TITLE
Invitation Letter Frontend

### ISSUE THREAD

**Issue by jaderabbit** [deep-learning-indaba/Baobab#331]
A registered attendee (which is what a candidate is known as after their registration is confirmed) can request an official invitation letter on their registration page. The system should generate a letter according to a predefined template and email it to the user as a PDF. This is outlined in the [Registration spec](https://docs.google.com/document/d/1dBTfmsBvWtCEw36mKYIgRsvMxE0BhMT-mU9iHVcWTrs/edit#)

If a user has completed registration process, the user should be able to see and click on an "Request Invitation Letter" link, which will take a user to an "Request Invitation Letter" page. 

The "Request Invitation Letter" page will have a form to capture the following new details required for the invitation letter: 

- The registered attendee’s passport number.
- The registered attendee’s passport name.
- The registered attendee’s password issued by date
- The registered attendee’s Passport issued by authority.
- The registered attendee’s work address
- The registered attendee’s residential address
- The person to whom the invitation letter should address

The following values for the user should be displayed (query from the user object):
"We have the following values required for your invitation from your user. Please go to the user page if you need to update them"

- The registered attendee’s Country of residence.
- The registered attendee’s Nationality.
- The registered attendee’s Date of Birth.

The submission button should call the POST method of invitation letter controller from #329. 
Once submission is complete, an appropriate success or error message should be displayed 

Dependant on completion of #329

**Comment by KaleabTessera** [comment]
1. Reg the "The person to whom the invitation letter should address" field, I don't know if people will know that. Is an example of this -  "Immigration Officer, UK Embassy"?
2. Regarding the address, I see the backend address field is 1 line. On the front end, we will record it as multiple lines, but when we save it, we need to delimit the lines. I am thinking of using ``` | ``` , I wanted to used a comma but the addresses themselves could have commas. 
Example:
Front-end
```
11 RandomPlace
Happy Park, Randburg
Johannesburg
2195
South Africa
```

Will be saved as ```11 RandomPlace | Happy Park, Randburg | Johannesburg | 2195 | South Africa``` in the backend. @jaderabbit @avishkar58 Does this sound okay?

**Comment by avishkar58** [comment]
@KaleabTessera 
Sorry for late response.
1. Yes, this would be something like "Kenyan Embassy" for visa applications or "Company X" for people using it to apply for funding etc.
2. Can't we save line-breaks in the database field ?

**Comment by KaleabTessera** [comment]
@avishkar58 No problem. Yeah thanks for point 2, lol can't believe I didn't just think of that.
