### ISSUE TITLE
Registration Administration Controller

### ISSUE THREAD

**Issue by jaderabbit** [deep-learning-indaba/Baobab#332]
A registration admin is in charge of tracking un-confirmed registrations and handling any processes that occur outside of Baobab to confirm these registrations (for example, liasing with the events organiser about registration fee payments for the Indaba 2019). Details in the [Registration Spec
](https://docs.google.com/document/d/1dBTfmsBvWtCEw36mKYIgRsvMxE0BhMT-mU9iHVcWTrs/edit#)

### New EventRole
- A new "registration-admin" event role must be added (just a string on user role)

### Endpoint: `/api/v1/registration/unconfirmed`
- GET a list of candidates with **unconfirmed** registrations: 

Request: 
```
{
   event_id: 1,
}
```

Response: An array of the following objects
``` 
[{
   registration_id: 1,
   user_id: 1,
   firstname: "Jeff",
   lastname: "Dean", 
   email: "jeff@googly.com",
   user_category: "Industry",
   affiliation: "Google",
   created_at: thedatetheregistrationwascreatedat
}]
```

### Endpoint: `/api/v1/registration/confirmed`
- GET a list of candidates with **confirmed** registrations: 
Request: 
```
{
   event_id: 1,
}
```

Response: An array of the following objects
``` 
[{
   registration_id: 1,
   user_id: 1,
   firstname: "Jeff",
   lastname: "Dean", 
   email: "jeff@googly.com",
   user_category: "Industry",
   affiliation: "Google",
   created_at: thedatetheregistrationwascreatedat
   attendance_id: null
}]
```
The `attendance_id` is populated from the attendance table. If a record exists, then the `attendance_id` is populated, else it is null

### Endpoint: `/api/v1/registration/confirm`
- POST 
```
{
   registration_id: 1
}
```
This will update the registration id to "confirmed" and send out the relevant "confirmed registration" email. 

Only a user with a registration administrator role can access these methods. 

Dependant on #334 

### Registration Confirmation Email Copy 

**Subject**: Your registration to <Event Name> has been confirmed!
**Body**:

Dear *User Name*

Your registration to the *Event Name* has been confirmed! This means that all required payment has been completed. We look forward to seeing you at the event

Kind Regards,
Deep Learning Indaba Team

**Comment by jaderabbit** [comment]
@avishkar58 Sanity check here pls :P

**Comment by avishkar58** [comment]
Looks Good To Me! :)
Just a note that at the moment EventRole is just a mapping from user_id to a string, so no migration is needed to create the new role - we should eventually have an EventRole table with a proper one-to-many relationship, but that's for another issue :)
