### ISSUE TITLE
Attendance Model

### ISSUE THREAD

**Issue by jaderabbit** [deep-learning-indaba/Baobab#334]
On the day of an event, a registration admin should be able to access an attendance page as described in the [Registration spec](https://docs.google.com/document/d/1dBTfmsBvWtCEw36mKYIgRsvMxE0BhMT-mU9iHVcWTrs/edit#). The following model must be created

**Attendance Model**
- id (pk)
- event_id (references event)
- user_id (references app_user)
- timestamp 
- updated_by_user_id (references app_user)

Required:
- Model
- Migration

**Comment by avishkar58** [comment]
@amritpurshotam : Great to have you back! :) :)

**Comment by amritpurshotam** [comment]
@avishkar58 sure glad to be back :)
