### ISSUE TITLE
Attendance Controller

### ISSUE THREAD

**Issue by jaderabbit** [deep-learning-indaba/Baobab#335]
On the day of an event, a registration admin should be able to access an attendance page and should be able to mark who has attended. Details in the [Registration Spec](https://docs.google.com/document/d/1dBTfmsBvWtCEw36mKYIgRsvMxE0BhMT-mU9iHVcWTrs/edit#)

### POST /api/v1/attendance
- This will create an attendance record for the user for the event. 
- This will send out a Welcome email to the user
- This will error if the event or user_id does not exist
- This will error if the attendance has already been confirmed
 
Request:
```
{
   event_id: 1,
   user_id: 1,
}
```
Response: 
```
{
   id: 1,
   event_id: 1,
   user_id: 1,
   timestamp: 1,
   updated_by_user_id: 1
}
```
### DEL /api/v1/attendance/:user_id

This will delete the attendance record for that particular user

### GET /api/v1/attendance/:user_id:

This will retrieve a user's attendance record and error if one does not exist:
```
{
   id: 1,
   event_id: 1,
   user_id: 1,
   timestamp: 1,
   updated_by_user_id: 1
}
```
### Welcome Email Copy

**Subject**: Welcome to *Event Name*
**Body**:
Dear *User Name*,

Welcome to the *Event Name*! We're so excited that you made it. 

If you have any trouble, please reach out to us on info@deeplearningindaba.com or ask any of our helpful volunteers.

Kind Regards,
The Deep Learning Indaba Team

@avishkar58 Do we need any extra info in the welcome email?

**Comment by avishkar58** [comment]
Looks great for now! We might update the email copy closer to the event (eg to say what colour t-shirts the organisers will be wearing or something like that)
