### ISSUE TITLE
Attendance Front End

### ISSUE THREAD

**Issue by jaderabbit** [deep-learning-indaba/Baobab#336]
On the day of an event, a registration admin should be able to access an event attendance page as per [Registration spec](https://docs.google.com/document/d/1dBTfmsBvWtCEw36mKYIgRsvMxE0BhMT-mU9iHVcWTrs/edit#)

The attendance page should list all of the people who have confirmed registrations for the event in a table (showing email, firstname, lastname, affiliation, user_category). (See #332 )

- The table should be sortable (sorted by lastname by default) and pageable  
- The table should have a search box that searches in any of the fields.
- A final column in the table should contain a button saying “Mark attendance” which will create a new attendance record and send a “welcome” email notification to the attendee (see #335 ).
- The registration_volunteer should get a visual notification when they mark someone’s attendance along with the ability to UNDO their action in the event that they mistakenly clicked the wrong button (also in #335 ).

**Comment by KaleabTessera** [comment]
Done.
