### ISSUE TITLE
Offer page says "on waiting list" if user did not apply

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#345]
Query if an application exists for the logged in user and event. If no application and no offer exists, display a message saying "you did not apply to attend <EVENT NAME>"

**Comment by KaleabTessera** [comment]
I think this was fixed @avishkar58 ?

**Comment by avishkar58** [comment]
Nope, this is still an issue as far as I can tell...

**Comment by arunavkonwar** [comment]
@avishkar58 I was wondering which API lets you query for an existing application. Would it be `applicationForm.service` or do I need to write a new service for this? Thanks for your help :)

**Comment by avishkar58** [comment]
Hey @arunavkonwar - yes that's the one - there is a [getResponse](https://github.com/deep-learning-indaba/Baobab/blob/b51ab28b8da4498e78fa88c5ac64932c5b1bc5c5/webapp/src/services/applicationForm/applicationForm.service.js#L39) function there which you can use
