### ISSUE TITLE
Form state gets copied between sections

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#41]
Steps to reproduce:
Open the app and navigate to the application form (Apply link in menu)
Enter some text in the "Question 1" text box
Click Next to go to the next section
The text previously entered is now in the "What is 2+2?" text box. This is despite the textboxes having different ids.

**Comment by KaleabTessera** [comment]
Do the textboxs have different value properties?

**Comment by avishkar58** [comment]
Ah, looks like I didn't set the value property, was just reading it in the onChange handler - will try set that and see

**Comment by avishkar58** [comment]
Issue was that I needed to provide a key property so react knows how to render properly . Fixed by #76
