### ISSUE TITLE
Implement file upload in application form front end

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#42]
Implement file-upload functionality in the application form front-end. Do this by sending a separate multipart/form-data POST request when saving the response to a dummy back-end REST endpoint (eg <URL>/file). The back-end should respond with a file-id, this file-id should then be included as the 'value' for the 'Answer' corresponding to the question asking for a file-upload. 

(Chat to @avishkar58 if this doesn't make sense :) )

**Comment by KaleabTessera** [comment]
Hi @avishkar58, just want to confirm this is part of the Application Form and not part of the Create Account form?

**Comment by avishkar58** [comment]
Hey, yes this is part of the application form

**Comment by avishkar58** [comment]
See:
- https://github.com/axios/axios/blob/master/examples/upload/index.html
