### ISSUE TITLE
Attendance Admin: Show accommodation award on confirmation dialog 

### ISSUE THREAD

**Issue by jaderabbit** [deep-learning-indaba/Baobab#423]
If a user has an offer with an accommodation award, then this should be displayed on the confirmation dialog. 

Please note, this needs to work for an invited guest, who has been given an accommodation award

**Comment by KaleabTessera** [comment]
I don't have access to the db from where I am now, does the user have `offer.accommodation_award` and `offer.accepted_accommodation_award` true?

**Comment by jaderabbit** [comment]
@KaleabTessera I shall check

**Comment by jaderabbit** [comment]
@KaleabTessera They do 
![image](https://user-images.githubusercontent.com/5547095/63520845-b0938400-c4f5-11e9-87ab-44a1384d6c11.png)

![image](https://user-images.githubusercontent.com/5547095/63520918-cbfe8f00-c4f5-11e9-8f26-048575109101.png)

**Comment by jaderabbit** [comment]
@KaleabTessera Note: This is a person who signed up as an "Invited Guest" on category, they're not ACTUALLY an invited guest (which is fine, just confusing for testing - wull update).
