### ISSUE TITLE
Attendance Admin: User with both normal registration and guest_registration are not indicated as "guests"

### ISSUE THREAD

**Issue by jaderabbit** [deep-learning-indaba/Baobab#426]
Attendance Admin: User with both normal registration and guest_registration are not indicated as "Invited Guests" 

![image](https://user-images.githubusercontent.com/5547095/63518680-db7bd900-c4f1-11e9-8c97-bb76012e1fb7.png)

**Comment by KaleabTessera** [comment]
Just want to confirm, is this user is in the InvitedGuest's table? We check there, rather than guest registration table now.

**Comment by jaderabbit** [comment]
@KaleabTessera You're correct. Badly constructed test case. Thank you
