### ISSUE TITLE
Simplify user profile

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#439]
- Remove all fields from user profile front-end except for title, firstname, lastname, email address and password
- Check that signup and profile update still works (might need to make some fields nullable in the backend for this to work properly). 
- Disable updating email address

**Comment by KaleabTessera** [comment]
@avishkar58 How about primary language? I can imagine when signing up, it might be useful to have primary language incase we want to show some home page stuff in our languages? 

This is obviously thinking long term.

**Comment by avishkar58** [comment]
Hey Kale-ab,

Let's remove it for now, we can always add it back if we ever get to
localising to other languages.. and even if we do, we can probably have a
locale selector thing on the page like other sites rather than as part of
the user profile...
