### ISSUE TITLE
Implement Response confirmation email

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#44]
Depends on #43 

Send a confirmation email when the user submits their response. 
This should be implemented in the POST method of the response API in app/api/responses/api.py and is triggered when the "is_submitted" flag is set to true in the request data. The email should be sent using api/app/utils/emailer.py. The email should be worded as follows (replace anything in angle brackets {} with the appropriate data)

```
Dear {User.title} {User.firstname} {User.lastname},

Thank you for applying to attend {Event.description}. Your application is being reviewed by our committee and we will get back to you as soon as possible. Included below is a copy of your responses.

{INSERT SUMMARY OF ANSWERS TO THE QUESTIONS IN THE RESPONSE}

Kind Regards,
The {Event.name} Organising Committee
```

**Definition of Done**
This task is done when

* The POST method in api/app/response/api.py has been updated to create the email message
* The emailer service is called to send the email
* A unit test exists for this functionality which mocks out the email service.

**Comment by avishkar58** [comment]
Response Controller has been implemented, so this is ready for someone to pick up

**Comment by Carvalho96v2** [comment]
I can jump on this

**Comment by Carvalho96v2** [comment]
Hey @avishkar58 , sorry this has taken so long, I've been pretty busy these past few days, looking at this now.

With regards to the unit test, because we're baking this into the post method, wouldn't the existing post method's unit test cover this too? Or would the unit test just cover the content and formatting of the email?

**Comment by avishkar58** [comment]
Hey, yes the existing POST unit test should be fine, but you might need to
mock out the email service since we don't want to send emails from tests..

**Comment by Carvalho96v2** [comment]
Okay cool, as of right now though we've only got filler data (SMTP host, ports, etc) for the emailer service, so emails don't send at all. Is this correct as is?

**Comment by avishkar58** [comment]
Yeah that's correct for now, the correct values get filled in between
CircleCI and GCP I believe - there's some on-going discussion around how to
do this for development - maybe we just use a mock service for development
too which writes to STDOUT or something?

**Comment by Carvalho96v2** [comment]
Okay sweet, yeah that sounds good
