### ISSUE TITLE
File API Improvement

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#442]
The current file API relies on guids to identify files in Blob storage, and when users retrieve files using the file API, they get a file with a GUID name. This is confusing for users and particularly problematic on windows where the file extension is important. 

Update this by introducing a File table that stores metadata about a file, including:
- id
- filename
- mime_type
- guid 

We need to maintain backward compatibility, as some clients have links to CVs using the GUID-based API. In order to do this, we will leave the GET method on the current API intact and remove the POST method. 

Introduce a new API (can be in the same file, api/app/files/api.py, but with a different route) that implements a POST and GET. The POST should save the file in Blob storage and add a record to the File table to store the metadata and return a file ID that identifies the file in the table. The GET method should take a fileID, query the File table, retrieve the document from blob storage, rename the file and set the appropriate mime_type before returning to the client.

**Comment by amritpurshotam** [comment]
Hi @BrainTheos. Let me know if you have any questions or need assistance with anything. Always happy to help :) 
And if you have some code in progress already and stuck, feel free to push it and open a PR anyway and then we can point you in the right direction.

**Comment by BrainTheos** [comment]
Hi @amritpurshotam and sorry for the delay. Here is what i tried to do : i created a File table in a new models.py at api/app/files/ which i import in api/app/files/api.py. In this api.py, i created a new API class with two methods : get and post as specified in the issue description. Now i'm a bit stacked on how to get file metadata argument to feed in our File() object (table) in order to save it !  Any idea ?

**Comment by amritpurshotam** [comment]
@BrainTheos I've updated the PR you submitted with my comments

**Comment by BrainTheos** [comment]
Well received with thanks.
I'm really happy to learn from your comments, and I highly appreciate your
help !
Hope I'll be done by wednesday !
Best regards!

Le lun. 10 févr. 2020 à 22:07, amritpurshotam <notifications@github.com> a
écrit :

**Comment by avishkar58** [comment]
This can be done in an easier way, by adding an optional `filename` parameter to the existing file API. The API then uses this name to rename the file before returning it to the user. The answer value for files can then be made into a JSON object that has the GUID and filename (similar to how the multi-file type works) and the front-end extracts this name and passes it to the backend.
