### ISSUE TITLE
Organisation white-labelling

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#449]
Update the front-end to get the logo and organisation name from the organisation api (depends on #450 ). Use the small_logo for the header image on the menu, use the system_name to replace "Baobab" in the title. 

Update the footer to say "(c) <organisation name> | Powered by Baobab" with a link to the organisation URL on the <organisation name> and a link to www.deeplearningindaba.com on the word "Baobab"

**Comment by arunavkonwar** [comment]
@avishkar58 Will this require creating a new controller in the `services` folder? or is there any other way I can talk with the organization API? Thanks

**Comment by avishkar58** [comment]
Hi @arunavkonwar , yes this would require a new service in the services folder to communicate with the organisation api (the endpoint is at /api/v1/organisation). Note that the API just returns the file name of the logo for the current organisation, so you'd need to dynamically load the relevant image based on this. I'll be sending a PR tomorrow morning that also adds a "system_name" property to Organisation, this should be used where "Baobab" appears at the moment in the top left corner of the menu :)
