### ISSUE TITLE
Research: EU regulations

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#451]
Since Baobab will be used by EEML in the EU, we need to ensure that we are compliant with EU regulations (GDPR in particular). Determine what changes we need to make to satisfy EU regulations and create issues to implement these.

**Comment by SMHall94** [comment]
@jaderabbit If you need any help on this point, let me know :D

**Comment by NileshArnaiya** [comment]
- Cookies used and display (This website uses cookies to ensure) popup
- Ability for user to **Delete User** Data (form) 
- Mentioning 3rd party services used (e.g. **Mailchimp** or Analytics) Links 
- Age validation on the registration form (16 or 18 years below) Currently accepts all ages 
- Suggestion: SSL certificate for DL Indaba
Rest seems fine to me in the privacy policy
