### ISSUE TITLE
Organisation and Event front-end changes

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#453]
Depends on organisation and event backend work

In order to support both multi-tenancy (through organisations) and multi-event (through events linked to organisations), we need to make the following changes to the structure of the front-end. 
 
- Move the existing front-end home component to be an "event-home"
- Update routes so that an event_key identifies and event (for example, baobab.deeplearningindaba.com/indaba2020 should go to the home page for the Deep Learning Indaba 2020 event)  
- Update other routes like "apply" so that <event_key>/apply identifies the apply page for the Indaba 2020 event
- Create a new organisation home page. This page should have no top-level menus which are now all event-based. 
- The organisation home page should query the event_api to get a list of upcoming events, with links to the home pages for those events.

**Comment by KaleabTessera** [comment]
Looks good. I don't mind taking this one, once we have the backend done.

**Comment by KaleabTessera** [comment]
Putting this on the bench, until I am done with https://github.com/deep-learning-indaba/Baobab/issues/439.

**Comment by avishkar58** [comment]
Will start on this one so long, might need some help with the event_key stuff
