### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#454]
Currently the app seems to be on Python2.7 (at least the docker container is). Upgrade to Python 3.8

**Comment by jainesh99** [comment]
Hi @avishkar58 ,
Is there a reason why version 3.8 was chosen, I did some reading and I see that the google app engine has both 2.7.9 and 3.7.2 installed.

**Comment by avishkar58** [comment]
Hey @jainesh99 - no reason, just wrote 3.8 because it was the latest version. We're not using app engine at the moment, but if there's generally better support for 3.7, then happy to go with that

**Comment by jainesh99** [comment]
Hi @jaderabbit , I just have a small question, is there a reason why the code in routes.py was copied into __init___ ?

**Comment by jainesh99** [comment]
Hi,
This ticket might take a little longer than I anticipated, it seems not so straightforward of a task.

**Comment by avishkar58** [comment]
No worries, thanks for the update! We did expect it to be quite non trivial
;)

**Comment by jaderabbit** [comment]
@jainesh99 No python import was allowing me to import the file. I don't know why - it was making me crazy

So I shoved it in the innit

**Comment by jainesh99** [comment]
Yes, I also noticed that as well :)
