### ISSUE TITLE
Resolve all Eslint warnings

### ISSUE THREAD

**Issue by bamtak** [deep-learning-indaba/Baobab#462]
When I run the program for the first time, I notice some Eslint warnings. 

> '===' and instead saw '==' , 
 'value' is defined but never used
Useless constructor
Arrow function expected a return value (some map and filter function returns null)

I have actually resolved all except the 

> href in < a />

 that I need access to some to see the styling before I make any update

**Comment by bamtak** [comment]
Please can I have a dev username and password that I can use to test locally? I can't seem to get am email if I register locally.

**Comment by avishkar58** [comment]
Hi Tajudeen,

Thanks for taking this!
When registering locally, keep an eye on your console to pick up your
verification link. The email gets logged there in development mode.

Thanks!

**Comment by bamtak** [comment]
Thank you.
I have completed the issue and make a pull request
