### ISSUE TITLE
Add POST and PUT to event api

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#473]
Add post and put methods to the event api (api/app/events/api/py) that allow updating the fields of a single event (everything on the Event model in api/app/events/models.py). 

If the current user is not an event_admin for the event they are trying to modify, return a FORBIDDEN error.

**Comment by s-mawjee** [comment]
@avishkar58  I'm keen to take this on.

**Comment by avishkar58** [comment]
Great thanks! Let me know if anything is unclear :) at the moment there is
an EventsAPI which is more like an "Event List" API, so you might need to
create a new EventAPI for single events

**Comment by s-mawjee** [comment]
Am I correct to assume that any user that `is_admin` can create an event? And on creation, the user is assigned as event admin?

**Comment by avishkar58** [comment]
Hey, yes that's correct :)
