### ISSUE TITLE
Add event configuration front-end

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#474]
Depends on #473 

Create functions in webapp/src/services/events to talk to the event API (api/app/events/api.py) 

Create a front-end page called eventConfig that allows the properties of the current event to be viewed and updated. 

Add a menu item linking to this new page under the "Event Admin" menu.

**Comment by s-mawjee** [comment]
I'll work on this.

Is there a UI layout?

**Comment by avishkar58** [comment]
Hey, there isn't one, if you're taking this issue, would you mind doing a
quick mockup? Thanks!

**Comment by s-mawjee** [comment]
The dropdown will contain the available events (that user has admin role). The user can `select an event from the dropdown` or `add event`. 

If the user selects an event, the `add event` button will be disabled. 
The update button will only be active if there was a change made.

Still need to add the other date-time fields. Will use a date-time-picker, for all the date-time fields. 

<img width="1664" alt="Screenshot 2020-01-30 at 07 55 54" src="https://user-images.githubusercontent.com/21179950/73423849-f884c580-4335-11ea-9689-cbe859c61ad0.png">

**Comment by s-mawjee** [comment]
When creating an event from the UI, is the user limited to a specific organisation? i.e `organisation_id` for event is defined by `g.organisation`

**Comment by avishkar58** [comment]
Hey Shahil,

Yes that's correct :)
