### ISSUE TITLE
Fix update word count in application form section.

### ISSUE THREAD

**Issue by EmmanuelTobi** [deep-learning-indaba/Baobab#477]
From the webapp/component/form/FormTextArea js file

**Comment by EmmanuelTobi** [comment]
assigning setState and onKeyPressed

**Comment by NileshArnaiya** [comment]
This looks good to me. I'll take it up

**Comment by EmmanuelTobi** [comment]
Already fixed tho. Will be closed soon.

**Comment by NileshArnaiya** [comment]
So the limit has been set to words? Okay cool! Thanks for updating

**Comment by amritpurshotam** [comment]
@EmmanuelTobi Thanks for helping out!
Was this resolved in PR #481? Looks like you did work on this so assigning this to you so no one else takes it up by accident :) 
And if this was resolved, we can close this issue then.

**Comment by EmmanuelTobi** [comment]
You welcome, amritpurshotam. It was already resolved in PR #481. Sorry for
any possible confusion there.

**Comment by amritpurshotam** [comment]
@EmmanuelTobi No worries at all. Just making sure :)
