### ISSUE TITLE
Improve documentation to make onboarding easier for new contributors

### ISSUE THREAD

**Issue by amritpurshotam** [deep-learning-indaba/Baobab#495]
Mention the following
* Put link of Google doc to volunteer.
* Mention that ideally branches should be created in this repo and not a fork so tests run
* How to contribute to a backend feature especially around migrations (see explanations in PR #472 )
* Explain how to do a migration script merge (use command in PR #490 )

Other
* Git flow best practices and general git conventions around branch naming and commit messages

**Comment by SMHall94** [comment]
I can help out with this :)

**Comment by amritpurshotam** [comment]
That would be awesome, thanks :)
