### ISSUE TITLE
Add ReferenceRequest entity

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#497]
As part of the awards process, add a new model called ReferenceRequest to a `models.py` file in a new folder `references` under api/app. The model should have the following fields:
- id (int, primary key)
- response_id (int, foreign key references Response)
- title (string)
- firstname (string)
- lastname (string)
- email (string)
- relation (string)
- email_sent (datetime)
- token (string)

Create a migration to apply the change to the database 

Create a repository with functions to query by id, to get all ReferenceRequests by response_id and to add a new ReferenceRequest. When adding a reference request, generate a new random GUID to use as the token.

**Comment by bamtak** [comment]
@avishkar58 I think there should be an email field (where to send the request to) on the ReferenceRequests entity.

**Comment by avishkar58** [comment]
Ah yes, quite correct, have added that to the description - thanks!  :)
