### ISSUE TITLE
Add ReferenceRequest API

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#498]
Depends on #497 

Add a new ReferenceRequestAPI controller to api/app/references/api.py with the the follow methods:

POST:
Accept and validate all fields on the ReferenceRequest model from the request (except email_sent and token) 

Insert a new ReferenceRequest in the database using the repository method

Determine the candidate (the logged in user) and the event (by loading the response and following the chain of references). Generate a link of the form [baobab_host]/[event.key]/reference?token=[token]

 (Todo @avishkar58 : how to handle nominations?)

Dear [title] [firstname] [lastname],

[Candidate.firstname] [candidate.lastname] has requested your reference for their application for the [event.description].

Please visit [link] to upload your reference by [event.application_close_date] 

Kind regards,
The [event.description] team.

GET:
retrieve a ReferenceRequest using the provided id

**Comment by bamtak** [comment]
@avishkar58  where is the token coming from 

`Generate a link of the form [baobab_host]/[event.key]/reference?token=[token]`

**Comment by avishkar58** [comment]
Hey, just updated #497 with the info on token :) thanks
