### ISSUE TITLE
Populate EEML Event and Application form configuration

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#503]
Create a new migration to add the following configuration to the database:

Event:
- organisation_id: 2   (EEML)
- name: Eastern European Machine Learning Summer School 2020
- description: Eastern European Machine Learning Summer School 2020, 6-11 July 2020, Krakow, Poland
- start_date: 6 July 2020
- end_date: 11 July 2020
- email_from: contact@eeml.eu
- key: eeml2020
- url: http://eeml.eu
- application_open: 28 January 2020
- application_close: 20 March 2020
Add any future dates for the other open and close dates for now

Application Form:
Create a new application form linked to the previously created event, set is_open to True and the deadline to 20 March 2020

Add sections and questions to the application form according to [this document](https://docs.google.com/document/d/1ZOL4E3sQCS8vCCHCLKQZUWwPHpepxW1NHQyPRWnr6kQ/edit?usp=sharing)

Take note of the following:
- The options field on the Question model should be a list of python dictionaries, with a label and value. So for example, to insert `"Yes"; "No"`  as options for a question, you would use `[{"value": "yes", "label": "Yes"}, {"value": "no", "label": "No"}]`
- The yellow highlighted items in the question tables are instructions to you, for example, for the country list, you'll need to create a list of countries to insert into the options field and for the validation you'll need to write a little **regex** to apply the validation. Everything else can be interpreted as a literal.

TIPS:
- To generate a new blank migration, run `docker-compose run web python ./api/run.py db migrate --directory api/migrations` in your terminal. This will create a new file in the api/migrations/versions folder. 
- Have a look at the [migration used to configure the Indaba 2019 application form](https://github.com/deep-learning-indaba/Baobab/blob/develop/api/migrations/versions/b3f7a73c98f3_.py) to see how it was done before. But keep in mind that the [models](https://github.com/deep-learning-indaba/Baobab/blob/develop/api/app/applicationModel/models.py) have been updated since then!

**Comment by Githugutech** [comment]
In Package-Management-Console type "Add-Migration InitialCreate" and  "update-database"

**Comment by Githugutech** [comment]
I can't get access
