### ISSUE TITLE
User Profile Profile Part 2

### ISSUE THREAD

**Issue by KaleabTessera** [deep-learning-indaba/Baobab#510]
Continues from https://github.com/deep-learning-indaba/Baobab/issues/439.

So user profile has been simplified to no longer need details such as nationality, gender, affiliation etc. However, there are some forms which require this form and attempt to get the data from AppUser table. 

These details will have to be collected outside of the app user, such as having this as a question or field in an application forms.

Forms to look at:
- Invitation Letter
- ReviewForm 
- ReviewHistory 
- Event Attendance
- Probably more tables.

**Comment by avishkar58** [comment]
Hey @KaleabTessera - is there anything specific you've worked on here? I've removed most of the references to the legacy UserProfile fields to get things working for EEML, and thinking we can raise separate issues for cases where we want to expose data from the application/registration form.

**Comment by KaleabTessera** [comment]
We can close this and create seperate issues.
