### ISSUE TITLE
Enforce some minimal complexity/strength in passwords

### ISSUE THREAD

**Issue by SMHall94** [deep-learning-indaba/Baobab#513]
One is able to sign up using only one character for the password. 
This might lead to potential security issues

**Comment by avishkar58** [comment]
Look for some libraries or guidelines for strong passwords, come up with a reasonable password policy (eg around length, numbers, special characters etc) that should be enforced or at least provide the user with a password strength indicator.

**Comment by SMHall94** [comment]
Some points for consideration in drafting a password policy:
- How long will the password last? 
- If I submit an application to one event, e.g. DLI, will I use the same password when I want to apply for next year's DL IndabaX?

**Comment by SMHall94** [comment]
Standard policy practise in terms of passwords:
- Min 6 characters, max 12 (upper limit is 28)
- Include at least one special character: valid values include numerals, capital letters, !, @, #, $, %, ^, &, or *. 
(perhaps a distinction should be made between capitals and characters to ensure added security?)

**Comment by TarCode** [comment]
https://github.com/deep-learning-indaba/Baobab/pull/616
