### ISSUE TITLE
Link to reset password redirects back to the DLIndaba test instance.

### ISSUE THREAD

**Issue by SMHall94** [deep-learning-indaba/Baobab#514]
- One is able to move between the two tabs (DLI and EEML)
- Having reset the password the password in one tab, one can still navigate the EEML test instance in another tab without having to sign in again.
Is it possible to reset the state so that once the password is reset, all other states are terminated?

**Comment by avishkar58** [comment]
Hey @SMHall94 - just to confirm, is the problem that the email you get for the password reset points to test-baobab.deeplearningindaba.com/...   instead of  test-portal.eeml.eu/...  ?

**Comment by SMHall94** [comment]
@avishkar58 I've updated the comment so it hopefully makes more sense. 
The points to test-baobab.deeplearningindaba.com/... instead of test-portal.eeml.eu/... ? was part of the issue that I forgot to log - apologies for the confusing issue !
