### ISSUE TITLE
Remove deadline from application_form

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#518]
Since events now have an application_close date, we should remove the deadline date from the ApplicationForm model and replace all of its usages with the event's application_close date.

**Comment by jainesh99** [comment]
I can try this one :)

**Comment by amritpurshotam** [comment]
@jainesh99 Reopening. I think we're still missing the migration to drop the deadline column

**Comment by avishkar58** [comment]
Oops! Good spot, totally missed that when reviewing the PR - thanks @amritpurshotam !

**Comment by jainesh99** [comment]
Gosh sorry about that, will get working on it asap.
