### ISSUE TITLE
Add Reference Entity and API

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#524]
Add a new Reference entity to api/app/references/models.py with the following fields:
- id (int, primary key)
- reference_request_id (int, foreign key references ReferenceRequest.id, not null)
- timestamp (datetime, not null)
- uploaded_document (int, foreign key references File.id)

Note: the File API might not yet have been updated (see #442), if that's the case, then make uploaded_document a string that will accept the uploaded file's GUID in Blob storage.

Create a migration to apply the change to the database and a new ReferenceRepository in api/app/references/repository.py with methods to query and insert records.

Create a new ReferenceAPI in api/app/references/api.py with the following methods:
**POST**:
- Accept a token and an uploaded_document reference as inputs
- Look up a ReferenceRequest using the token and the [ReferenceRequestRepository](https://github.com/deep-learning-indaba/Baobab/blob/develop/api/app/references/repository.py)  (you may need to add a new method to this repository)
- Insert a new Reference entity in the database

**GET**:
- Verify that the logged in user is an event admin
- Given a response_id, look up the corresponding References (via ReferenceRequest) and return a list of these

**Comment by bamtak** [comment]
@avishkar58 
1) Is authentication required for ReferenceAPI POST request (Do user need to login to upload a reference)
2) How do we track if a reference request has been fulfilled (To avoid duplicates)

**Comment by avishkar58** [comment]
Hey @bamtak ,

1. Authentication is not required to upload a reference (these will generally come from university professors etc who probably won't be applying for any Indaba events, so we don't need to give them the additional burden of signing up for an account :) - that was the motivation for using the GUID token instead)

 2. Good point, maybe you can add some logic to return an error if there is already a Reference for the matching ReferenceRequest and update the ReferenceRequest API to add a flag in the GET response if there is already a Reference for that ReferenceRequest?
