### ISSUE TITLE
Add a Reference Request Component

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#526]
Add a new front-end component to webapp/src/components which allows users to enter the details of people they want to request referrals/(letters of support) from. 

The component should accept the following properties
- min_num_referrals
- max_num_referrals

The component should then display a list of rows (starting with min_num_referrals rows), each row prompting the user to enter the Title, Firstname, Lastname, Relation and Email address of the person they want to ask for a referral. 

num_referrals refers to the current number of rows displayed in the list.
If max_num_referrals > num_referrals, add a "Plus" button which will add a new row to the list. 
If min_num_referrals < num_referrals, add a minus/trash button to extra rows which will remove them

The current "value" of the component should be represented in a JSON list, something like:

[
  {
    "title": 'Prof.", 
    "firstname": 'Jane",
    "lastname": 'Bloggs",
    "relation": 'Supervisor",
    "email": "jane@bloggs.com" 
  },
  {
    "title": 'Mr.", 
    "firstname": 'Idris",
    "lastname": 'Elba",
    "relation": 'Friend",
    "email": "idris@elba.com" 
  }
]

The component should support the value being set as a property, so that it can be used in a form.

**Comment by avishkar58** [comment]
Hey @jaderabbit - are you working on this?

**Comment by jaderabbit** [comment]
@avishkar58 I started at the hackathon but then got caught up in helping things :) SO no, shall remove myself
