### ISSUE TITLE
Populate Application Form

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#54]
Create a script/migration that populates data in the Event, ApplicationForm, Section and Question tables for the 2019 Indaba. The application form should be based on [last year's form](https://docs.google.com/forms/d/1sBLYJtrvYmfxykrJCVmKFWEvVE6ZBx9-6kLLy2QlVYo/edit) with the following changes:

1. Exclude the personal information section, as most of these details are now captured in the user account creation form
2. Add a section called "Previous attendance" with the following questions: 
- "Did you attend the 2017 or 2018 Indaba" - options: 2017, 2018, 2017 and 2018, Neither
- "If you attended a previous Indaba, tell us how it has helped you grow or how you have used what you have learnt."
3. Leave out the "Your skills and experience" section - we will not be asking these questions in the 2019 application form. 

See [this migration](https://github.com/deep-learning-indaba/Baobab/blob/develop/api/migrations/versions/c8d762cf6784_.py) for an example of how to seed static data with bulk_insert

**Comment by Carvalho96v2** [comment]
I can jump on this

**Comment by Carvalho96v2** [comment]
@avishkar58 should we add an "is_required" field to the question table?

Also, how do you think we should handle the canned options (a la "* 017, 2018, 2017 and 2018, Neither")? A separate table linked to the specific question via question_id, or an added nullable JSON field to the question table?

**Comment by avishkar58** [comment]
Hey @Carvalho96v2 - thanks for picking this one up! An is_required field makes sense, lets go with the nullable JSON field on the question table, so this can be passed easily to the front-end which can then decide how to display it.

**Comment by Carvalho96v2** [comment]
@avishkar58 Sweet! Thanks for the quick response :)
