### ISSUE TITLE
Update response API to cater for nominations

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#560]
Depends on #559 

We need to cater for certain events (and application forms) allowing people to **nominate** someone else (eg for Indaba awards). This means that we should allow multiple responses when the application form's `nominations` flag set to True. If the application form has `nominations` set to false, then we assume that the response is for the logged in user. 

In the file https://github.com/deep-learning-indaba/Baobab/blob/develop/api/app/responses/api.py

## Update `ResponseAPI` the GET method:
- Return a list of all responses instead of just the first one

## Update the `ResponseAPI` POST method:
- Raise a duplicate error if the `nominations` flag is set to false and a Response already exists for the logged in user and event

Cleanup:
- Replace any existing direct queries (`db.session.query(....)`) with calls to the response repository

**Comment by amritpurshotam** [comment]
@avishkar58 Will there be multiple application forms now per event? The normal application and the nomination application? Will need to double check but I think a lot of the logic in the app assumes one application form per event.

**Comment by avishkar58** [comment]
Nah, there will still only be one application form per event, and it will
either be nominations or no nominations (eg the awards will have one
application form with nominations set to true and people can nominate
themselves)

**Comment by amritpurshotam** [comment]
@avishkar58 Okay I think I see what you're doing now. Is there a requirement for a motivation why? I'd imagine that would could be a Question and whatever they say will be the Answer. Just trying to figure out the full flow of how this will work because at some point all the nominations will have to be grouped somehow and the code will have to work no matter the event, application form, or question

**Comment by avishkar58** [comment]
Yeah that will be a question in the application form :) the design of this
is probably quite suboptimal.. do you have any suggestions for improving
it?

**Comment by amritpurshotam** [comment]
I've been mulling over a few designs (all suboptimal) but I realised there's already something there. Sections! I forgot about that until looking at the models again now. So we can have a Nomination section.
Also I think we need a way to generate the ERD from the database directly. I'll look to see if there's an easy way to do it in Postgres, Would have that solution pop out a little more obviously.

**Comment by amritpurshotam** [comment]
@avishkar58 I just had another thought now. Would we even need the response to store the nomination title, firstname, etc and the nominations flag on the ApplicationForm model? Can that not just be configurable with the Nomination Section and Questions?

**Comment by avishkar58** [comment]
Hmmm yeah your design definitely sounds simpler and cleaner than mine and
solves an issue with the award form that I was struggling to think through
yesterday (that there are additional details about the nominee that we want
to capture, which under the current design wouldn't be in the same place we
capture the name of the nominee) We'll still need the nominations flag or
something similar though to allow having multiple responses (someone can
nominate multiple people), vs single response (an individual can only
submit one application to the main Indaba for example).

**Comment by avishkar58** [comment]
@amritpurshotam I'll start updating the relevant issues accordingly, sorry for the wasted effort on updating the model!

**Comment by amritpurshotam** [comment]
@avishkar58 Sure no worries. I didn't spend that long on creating those models. Should be easy to remove those fields as well. 
If we're only having one application form, how will we allow someone to nominate multiple people without completing all the other questions again?

**Comment by avishkar58** [comment]
Well.. that design change significantly simplifies things! :D :D 
Yes, the awards will be a separate event.

**Comment by amritpurshotam** [comment]
@avishkar58 Haha thanks 😄 
And yeah the separate event makes sense 👍
