### ISSUE TITLE
Add edit button to application form

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#562]
At the moment, after the user submits an application, we have a withdraw button which sets a flag on their application to say that it's withdrawn. They are able to then recover their application, edit it and resubmit it. Users would like to also have an edit button that allows them to update their application without it being withdrawn (and prevent mistakenly not being considered for an event!) 

Add an Edit button to the application form which opens up the response for editing, but does *not* set the withdrawn flag. This should be doable entirely in the front-end by adding a new flag to the state.

**Comment by CilliersN** [comment]
@avishkar58 
Im picking this up. This ticket is related to #136 & #146 correct?

**Comment by CilliersN** [comment]
if so ill link the 3 of them in my pr

**Comment by avishkar58** [comment]
Hey @CilliersN, that's right, they're all related - thanks!

**Comment by avishkar58** [comment]
Hey @CilliersN - are you still working on this one?

**Comment by CilliersN** [comment]
Hi @avishkar58 
sooo sorry. Ive done this already. only see now I havent made the pr yet 🙈 
things got super busy at work. I dont have my personal laptop with me now. will push the PR tomorrow
