### ISSUE TITLE
Remove Deep Learning Indaba logo from error page

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#563]
Update the [error page](https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/components/ErrorPage.jsx) to remove the Deep Learning Indaba logo. Also add a note that the bug report email will go to the Baobab team at the Deep Learning Indaba who maintain the application.

**Comment by CilliersN** [comment]
@ShingaiJP , whats the status on the ticket? do you need help with this?

**Comment by ShingaiJP** [comment]
Done with the ticket, will PR now 👍. Was just trying to get familiar
