### ISSUE TITLE
Reset password screen: button fix & small screen scaling

### ISSUE THREAD

**Issue by CilliersN** [deep-learning-indaba/Baobab#566]
center and align button
<img width="470" alt="Screenshot 2020-02-11 at 09 22 27" src="https://user-images.githubusercontent.com/29726916/74217472-2e1f9c00-4cb0-11ea-8607-577eeb9e696d.png">

<img width="388" alt="Screenshot 2020-02-11 at 10 39 37" src="https://user-images.githubusercontent.com/29726916/74221535-01bd4d00-4cbb-11ea-97aa-5a1f5332e99c.png">

**Comment by CilliersN** [comment]
cant assign mysef to it (dont think i have permissions) 
buit will work on it

**Comment by amritpurshotam** [comment]
@CilliersN Have you checked your email? I see an invitation has been sent

**Comment by CilliersN** [comment]
Hi @amritpurshotam, I have, there's nothing.
Also not getting any emails from sign up screen.
accessing local instance on port 8080. 
created account and getting 
"Your Deep Learning Indaba account has been created, but before you can use it, we need to verify your email address. Please check your email (and spam folder) for a message containing a link to verify your email address."

also no email. did check spam folders

**Comment by amritpurshotam** [comment]
@CilliersN Try navigating to https://github.com/deep-learning-indaba/Baobab/invitations and see what happens?

As for activating your account, I think since you're on local, no emails are actually sent. I think check your terminal though. The emails are logged there so you should see your link somewhere I think.

**Comment by CilliersN** [comment]
Got it, thanx @amritpurshotam
