### ISSUE TITLE
Remove loading of unused content

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#587]
[This file](https://github.com/deep-learning-indaba/Baobab/blob/b7e77f8804b81fbb694651e5a3614b2f18632767/webapp/src/utils/validation/contentHelpers.js#L3) loads a bunch of content that is no longer required. Remove all of these except for "title"

**Comment by TarCode** [comment]
Looks like `getCounties` is still being used by `Address.js`, `InvitationLetterForm.js` and `getGenderOptions` is still being used by `InvitedGuestComponent`.

I'll go ahead and remove the unused content (`getCategories`,  `getEthnicityOptions` and `getDisabilityOptions`)
