### ISSUE TITLE
Update User Profile List Front-end

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#593]
Update the [UserProfileList](https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/pages/profileList/components/ProfileListComponent.js) component with the following changes:
- Remove Category, Affiliation, Nationality and Department from the table
- Add `type` to the table (the back-end will set this to "Candidate" or "Invited Guest" (see ...)
- Update the redirect in the [`onSubmit` function](https://github.com/deep-learning-indaba/Baobab/blob/bf99909f71ef7cca4923d3a93ddcea9e6d443ccf/webapp/src/pages/profileList/components/ProfileListComponent.js#L37) to include the event key in the URL (the event_key can be obtained from props.match.params, see [here](https://github.com/deep-learning-indaba/Baobab/blob/d81fc6f826f1c55ef643dd5d99a49295eb741cdc/webapp/src/pages/eventHome/EventHome.js#L220) for an example). So the URL will be something like `/<event_key>/viewprofile/<user_id>`

**Comment by TarCode** [comment]
https://github.com/deep-learning-indaba/Baobab/pull/620
