### ISSUE TITLE
Split events list into upcoming events and awards

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#600]
On the [Organisation Home page](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/webapp/src/pages/home/Home.js#L89), split the Upcoming Events section into "Upcoming Events" and "Awards". Upcoming Events should only show events with `event_type` of "EVENT" and Awards should only show events with an `event_type` of "AWARD". You may also need to update the [back-end API](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/api/app/events/api.py#L27) to return the `event_type` field

**Comment by scott-glover020** [comment]
Hey @kalru I helped out with the back end changes, sorry don't have to much experience with the front end. You can find the branch and pr here https://github.com/deep-learning-indaba/Baobab/pull/621
