### ISSUE TITLE
Add a MultiCheckbox component

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#604]
Add a new form component in the file webapp/src/components/form/FormMultiCheckbox.js 

This component should represent a group of inline checkboxes with the following functionality:
- There should be a checkbox for each item in the props.options passed to the component (this will be a JSON array)
- When the state of any checkbox in the group is changed, call the `props.onChange` function with a JSON array of the labels of the checked checkboxes.
- Set the state of the checkboxes according to the value of `props.value`
- Add support for this component to the [ApplicationForm](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/webapp/src/pages/applicationForm/components/ApplicationForm.js#L69), [RegistrationForm](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/webapp/src/pages/registration/components/RegistrationComponent.js#L331) and [ReviewForm](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/webapp/src/pages/review/components/ReviewForm.js#L44) for questions of type "multi-checkbox"

For example, we might configure a question to have type multi-checkbox, with options ["Indaba 2017", "Indaba 2018", "Indaba 2019"]. The component should render 3 checkboxes, labelled  "Indaba 2017", "Indaba 2018" and "Indaba 2019" respectively. If the user selects "Indaba 2017" and "Indaba 2019", the value sent to the props.onChange function should be ["Indaba 2017", "Indaba 2019"]

**Comment by ElanVB** [comment]
Hey, I jumped on this for the Hackathon and left my progress in PR #627 . I don't know if I will be able to finish it in a timely manner, so I unassigned myself for now. If anyone else has the time, feel free to finish my work (or start from scratch if it is trash) :)
