### ISSUE TITLE
Configure Maathai Impact Award Event and Application Form

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#609]
Create a migration that inserts the following new records into our database:
- Add an [event](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/api/app/events/models.py#L12) with the following data:
  - name: Wangari Maathai Impact Award 2020
  - description: Wangari Maathai Impact Award 2020
  - start_date: 23 August 2020
  - end_date: 28 August 2020
  - key: maathai2020
  - organisation_id: 1
  - email_from: baobab@deeplearningindaba.com
  - url: http://www.deeplearningindaba.com
  - application_open: 1 March 2020
  - application_close: 17 April 2020
  - review_open: 25 April 2020
  - review_close: 15 May 2020
  - selection_open: 1 Jan 2020
  - selection_close: 1 Jan 2020
  - offer_open: 1 Jan 2020
  - offer_close: 1 Jan 2020
  - registration_open: 1 Jan 2020
  - registration_close: 1 Jan 2020
  - event_type: AWARD

- Add an [application_form](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/api/app/applicationModel/models.py#L4) with the following data
  - event_id: The one created above!
  - nominations: True

- Configure the [Sections](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/api/app/applicationModel/models.py#L20) and [Questions](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/api/app/applicationModel/models.py#L35) according to [this document](https://docs.google.com/document/d/1MIt4F8_MIhYQcNFS-wLfQSCsxEYttvA7EhNLbY5pBZI/edit?usp=sharing)

Have a look at [previous migrations](https://github.com/deep-learning-indaba/Baobab/blob/develop/api/migrations/versions/87213d612eaf_eeml_application_form.py) for inspiration (although note that the data model may have changed since then!)

**Comment by OdendaalG** [comment]
Hi @avishkar58, I started working on this issue, but when I wanted to migrate it said it couldn't find a certain migration file. It is the same one that I was working on in issue #611 before I continue further, is there a way to reset and start from origin/develop because I'm assuming its because of local files? I even removed all the files and clones the repository from scratch.

**Comment by avishkar58** [comment]
Hey @OdendaalG - this is most likely because your database was already upgraded to the version in your other branch, and since that migration wasn't in develop, it now sees that the DB state no longer matches the code. 
I just merged your PR into develop now, so if you pull the latest develop and merge it into your branch it should work now. In future though you have two options if you've upgraded your database using a migration in a branch - you can downgrade it to start from the current state of develop again (but then you'll get a multi-head issue later on). Or you can create a new branch from your previous one, so in this case for example you could have checked out the issue-611 branch and did `git checkout -b issue-609` from there 

Hope this makes sense :)

**Comment by OdendaalG** [comment]
Hi @avishkar58 , I checkout out the issue-611 branch and then checked out issue-609 branch from there! Thank you!
