### ISSUE TITLE
Add Ethnicity List

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#61]
The ethnicity field on the Create Account form should be a selection box with the following options (as per the South African demographic groups, for reporting)
Black, 
Coloured / Mixed Descent,
White,
Indian Descent,
Other

**Comment by danielamassiceti** [comment]
Hey @KaleabTessera. As a first-timer, I would like to give this a go! Let me know if you've already started, otherwise I can take over :)
