### ISSUE TITLE
Configure Kambule Masters Award 2020

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#610]
Create a migration that inserts the following new records into our database:
- Add an [event](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/api/app/events/models.py#L12) with the following data:
  - name: Thamsanqa Kambule Masters Dissertation Award 2020
  - description: Thamsanqa Kambule Masters Dissertation Award 2020
  - start_date: 23 August 2020
  - end_date: 28 August 2020
  - key: kambulemasters2020
  - organisation_id: 1
  - email_from: baobab@deeplearningindaba.com
  - url: http://www.deeplearningindaba.com
  - application_open: 1 March 2020
  - application_close: 17 April 2020
  - review_open: 25 April 2020
  - review_close: 15 May 2020
  - selection_open: 1 Jan 2020
  - selection_close: 1 Jan 2020
  - offer_open: 1 Jan 2020
  - offer_close: 1 Jan 2020
  - registration_open: 1 Jan 2020
  - registration_close: 1 Jan 2020
  - event_type: AWARD

- Add an [application_form](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/api/app/applicationModel/models.py#L4) with the following data
  - event_id: The one created above!
  - nominations: True

- Configure the [Sections](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/api/app/applicationModel/models.py#L20) and [Questions](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/api/app/applicationModel/models.py#L35) according to [this document](https://docs.google.com/document/d/1YaXdrAGogcRyotLwybyNLKETUM6hhKY6NzyAaGw0vbs/edit#heading=h.n8mt72nzmyr9)

Have a look at [previous migrations](https://github.com/deep-learning-indaba/Baobab/blob/develop/api/migrations/versions/87213d612eaf_eeml_application_form.py) for inspiration (although note that the data model may have changed since then!)

**Comment by EmmanuelTobi** [comment]
Want to try taking this up.
