### ISSUE TITLE
Configure Kambule Doctoral Dissertation Award 2020

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#611]
Create a migration that inserts the following new records into our database:
- Add an [event](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/api/app/events/models.py#L12) with the following data:
  - name: Thamsanqa Kambule Doctoral Dissertation Award 2020
  - description: Thamsanqa Kambule Doctoral Dissertation Award 2020
  - start_date: 23 August 2020
  - end_date: 28 August 2020
  - key: kambuledoctoral2020
  - organisation_id: 1
  - email_from: baobab@deeplearningindaba.com
  - url: http://www.deeplearningindaba.com
  - application_open: 1 March 2020
  - application_close: 17 April 2020
  - review_open: 25 April 2020
  - review_close: 15 May 2020
  - selection_open: 1 Jan 2020
  - selection_close: 1 Jan 2020
  - offer_open: 1 Jan 2020
  - offer_close: 1 Jan 2020
  - registration_open: 1 Jan 2020
  - registration_close: 1 Jan 2020
  - event_type: AWARD

- Add an [application_form](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/api/app/applicationModel/models.py#L4) with the following data
  - event_id: The one created above!
  - nominations: True

- Configure the [Sections](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/api/app/applicationModel/models.py#L20) and [Questions](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/api/app/applicationModel/models.py#L35) according to [this document](https://docs.google.com/document/d/19f8DvO806ZJ2UQxgvjs-lJo7B8waAd-_qixk3hv57Zk/edit#heading=h.n8mt72nzmyr9)

Have a look at [previous migrations](https://github.com/deep-learning-indaba/Baobab/blob/develop/api/migrations/versions/87213d612eaf_eeml_application_form.py) for inspiration (although note that the data model may have changed since then!)

**Comment by avishkar58** [comment]
Hey @OdendaalG - you mentioned you might be having some issues with the migration on this task? Can you describe the problem - I can probably help :)

**Comment by OdendaalG** [comment]
Hi @avishkar58 , thank you for the reply. I have nearly completed this migration but have a few snag points. I followed the previous migrations and added the new event. The classes that were present in the mentioned migration were: Organisation, Country, Event, ApplicationForm, Section, and Question. I had included them all in the new migration and tried to upgrade the DB, it kept giving the following error:
"When initializing mapper mapped class X->x, expression 'Y' failed to locate a name ("name 'Y' is not defined")."
where X and Y would be class names it references. I then started adding the classes (like AppUser, EmailTemplate, UserCategory, UserComment, EventRole).
Adding the classes seemed to solve the errors, I am assuming it is because of the data model that has changed since the example migration. Does this seem correct or have I gone astray?
The error I am encountering now is "sqlalchemy.exc.NoForeignKeysError", where it says it could not determine the join condition between the two tables. I can link the migration file if that would help?
Kind regards and thank you in advance.

**Comment by avishkar58** [comment]
Hey,
Thanks for the explanation - please do link the migration file so I can
have a look. You might just need to remove some of the references from the
event/question etc to prevent having to bring in EVERY model :)

**Comment by OdendaalG** [comment]
https://drive.google.com/open?id=1CoMP11ffuTVYb5euJkUG4D3o_iHIatF0
As Github's comments don't allow python files, I uploaded it to a google drive and got the shareable link. Any advice on what to replace/remove the references with such that it doesn't damage anything down the line would be awesome :)

**Comment by OdendaalG** [comment]
Hi @avishkar58 , a better way to link the code (I have just been informed) is to open a PR and then ask. I'll be doing that shortly.

**Comment by avishkar58** [comment]
Hey @OdendaalG - so you can resolve this by removing the "db.relationship" lines from the models: for example in the Event model, remove these lines: 
```
organisation = db.relationship('Organisation', foreign_keys=[organisation_id])
application_forms = db.relationship('ApplicationForm')
email_templates = db.relationship('EmailTemplate')
event_roles = db.relationship('EventRole')
```

Then you won't need to define those models in the file. You'll notice these db.references aren't in the example migration - that was on purpose rather than the data model having changed :)

**Comment by OdendaalG** [comment]
Awesome, thanks! I made the changes. Two additional minor questions: How do I ensure that a dependency is met before requiring a question? It stems from the Doctoral Candidate Information section that is only required (first 4 questions) when the nominator is not the candidate? And how can I go about testing that it works? I assume by opening the webapp and navigating to the awards section?

**Comment by avishkar58** [comment]
So you'll have to wait for #622 to land, which will add the `depends_on_question_id` and `show_for_values` fields that you can set for the dependencies. Yes you can test on your locally running instance of the web app, but note that in development mode the app defaults to the "localhost" organisation and you're adding a new event in the Indaba organisation. To see the Indaba organisation locally you can use pgAdmin (or whatever tool you prefer to connect to the database) to update the organisation table and set the domain on organisation 1 to "localhost" and on organisation 3 to something else, then make sure to restart the application because it caches the organisation information. Also note that the dependency part won't work yet until #602 is done.

**Comment by OdendaalG** [comment]
Awesome, thanks so much for all the help! Will keep my eye on those two issues and then implement the final dependencies when they resolve.

**Comment by avishkar58** [comment]
Hey @OdendaalG - #622 is in now, so you can proceed with adding the dependency information - don't worry about testing the conditional logic on the front-end, we will test that all together once all the other functionality has been implemented :)

**Comment by OdendaalG** [comment]
I will add the dependency information as soon as possible! Thanks for the update!
