### ISSUE TITLE
Fix intermittent Circle CI/ Docker issues

### ISSUE THREAD

**Issue by KaleabTessera** [deep-learning-indaba/Baobab#648]
So sometimes the build fails because Circle CI fails to pull a docker container. 

I believe this usually occurs on the db image (based on orchardup/postgresql container). This issue is intermittent and restarting the build usually fixes it.

Error:
```
Pulling db (orchardup/postgresql:la****)...
ERROR: unexpected EOF
```

This could just be a network or cds issue on Circle CI or a bigger issue related to the image itself (https://github.com/orchardup/docker-postgresql) , e.g. the image we use is deprecated and there is now an official postgres docker image - https://registry.hub.docker.com/_/postgres/. Maybe we should move over to that.

**Comment by avishkar58** [comment]
This hasn't happened for a while now, so closing.
