### ISSUE TITLE
Add Outcome model

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#651]
## Motivation
At the moment, Baobab has no way to explicitly indicate the outcome of a candidate's application to an event. We previously relied on the existence of an offer to signal that a candidate was accepted, and assumed everyone else was on the waiting list. This does not give us sufficient granularity to determine whether selection has not completed yet, or someone has no chance of being accepted (ie has been rejected). This series of issues aims to introduce the concept of an application outcome to Baobab.

## Requirements
Add a new back-end model to a new models.py file in the new sub-directory (api/app/outcome/models.py) called Outcome which has the following properties:
- id (int, primary key, not null)
- user_id (int, foreign key references AppUser, not null)
- event_id (int, foreign key references Event, not null)
- status (enum[accepted, rejected, waitlist], not null)
- timestamp (datetime, not null)
- latest (bool, not null)

Create a migration to apply the change to the database.

**Comment by KaleabTessera** [comment]
I think it will be useful to have an "updated_by" field, that gives the user id of the event_admin who decided on the outcome.  It will make it easier to trace what happens, in case something like multiple admins decide on an outcome for a single user.
