### ISSUE TITLE
Add Outcome API

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#652]
## Dependency
Depends on #651 

## Motivation
At the moment, Baobab has no way to explicitly indicate the outcome of a candidate's application to an event. We previously relied on the existence of an offer to signal that a candidate was accepted, and assumed everyone else was on the waiting list. This does not give us sufficient granularity to determine whether selection has not completed yet, or someone has no chance of being accepted (ie has been rejected). This series of issues aims to introduce the concept of an application outcome to Baobab.

## Requirements
Add a new api.py to api/app/outcome with the following APIs:
#### GET method:
- Requires authentication
- Accepts event_id as parameter
- Retrieve and return the latest outcome (has latest flag set) for the logged in user and specified event via a new repository method

#### POST method
- Requires authentication
- Accepts user_id, event_id and outcome as parameters
- Validate that the user_id and event_id exists and that the logged in user is event_admin for the event
- Validate that the outcome is "accepted", "rejected" or "waitlist"
- Query for any existing Outcome instances for the given user_id and event_id and updated the latest flag to 0
- Create a new Outcome instance and add it to the database via a repository method
- Send an email to the user informing them of the outcome decision

#### GET method:
- Requires authentication
- Accept event_id as parameter
- Validate that an event with the given event_id exists
- Validate that the logged in user is an event_admin for the event
- Retrieve the list of Outcomes (with latest flag set to true) for the given event via a repository method
- Return the following fields: [user.user_title, user.firstname, user.lastname, user.email, outcome.status, outcome.timestamp]

Add appropriate routes to [routes.py](https://github.com/deep-learning-indaba/Baobab/blob/develop/api/app/routes.py)

**Comment by KaleabTessera** [comment]
Looks good. Any rules about transitions between outcomes, like can a person go from "rejected" to "waitlist"?

**Comment by avishkar58** [comment]
@KaleabTessera Thanks for the comments. I think we can leave the transition rules up to the people doing the selection for now and maybe enforce some rules later one once we see how it goes with EEML and maybe Khipu :)
