### ISSUE TITLE
Logging - Phase 1

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#67]
Ensure that all operations in back-end controllers (User, ApplicationForm, Response) are logged sensibly so that we can debug any issues that might occur when the app is in testing / production. This also involves determining where logs are stored and how they can be accessed when the application is running in GCP

**Comment by nischalhp** [comment]
@avishkar58 are we thinking of using ELK stack to evaluate logs on GCP? The storage will depend on how we want to use these logs. If we are going to setup ELK, then we can ship the logs from our docker containers by redirecting the logs to standard out and use logstash forwarder to push logs to centralized ELK server. That will give us the capability to also visualize the logs via Kibana as well. Based on the approach you think is feasible, I can take this task up.

**Comment by avishkar58** [comment]
@KaleabTessera @jaderabbit Any opinions on this?

**Comment by Carvalho96v2** [comment]
If I could weigh in on this, I've worked with the ELK stack once before for capturing logging, and it was great. It cut support time almost in half, and we were now able to spot and diagnose issues before a ticket was even logged. Granted I didn't set it up, so I'm not sure how much complexity lies in that, and we are pretty crunched for time, but I think it would definitely be a boon to have it at some point.

**Comment by jaderabbit** [comment]
@avishkar58 In my opinion, ELK is overkill. This is deployed via the app engine. It has error reporting and logs.

**Comment by KaleabTessera** [comment]
I agree with @Jade. For now it might be better to see that our logs propagate to the App Engine logs and see info related to how long the logs last, what is their pricing and also a better way to view them,

**Comment by jaderabbit** [comment]
So, the logs are [here](https://console.cloud.google.com/project/_/logs?_ga=2.41553766.-598322592.1549104313&_gac=1.218285675.1550686062.CjwKCAiAkrTjBRAoEiwAXpf9CdtmC9YUavX1Cdls0EnpZlmo4jd0bMlHBzxA5x5_iSZ0cP-eeLVtgxoCFygQAvD_BwE), if you have access to the project. 

Seems to capture everything and has filters and everything. Super nice

**Comment by avishkar58** [comment]
That looks great! So now we just need to make sure we're logging sensible information from our controllers :)

**Comment by greg-newman** [comment]
I wouldn't mind taking this if there are no objections? I think it would help me familiarise myself with everything.

**Comment by jaderabbit** [comment]
@greg-newman Go for it!

**Comment by nischalhp** [comment]
> So, the logs are [here](https://console.cloud.google.com/project/_/logs?_ga=2.41553766.-598322592.1549104313&_gac=1.218285675.1550686062.CjwKCAiAkrTjBRAoEiwAXpf9CdtmC9YUavX1Cdls0EnpZlmo4jd0bMlHBzxA5x5_iSZ0cP-eeLVtgxoCFygQAvD_BwE), if you have access to the project.
> 
> Seems to capture everything and has filters and everything. Super nice

Could I get access to the project? would love to see the logs and see if we can setup some alerts in place.

**Comment by avishkar58** [comment]
@nischalhp Added you as logging admin on GCP - let me know if you need any more permissions.

**Comment by nischalhp** [comment]
@avishkar58  I still cannot see the project. I am assuming you used nischal.hp@gmail to provide the permissions.
