### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#68]
Create a Google Analytics account and add it to the front-end

**Comment by kimibeyl** [comment]
will be able to help

**Comment by KaleabTessera** [comment]
Basic version of this has been added. Page views are recorded.

What still needs to be done:
- Virtual Page Views/Clicks  to record how many people are at what stage of filling out application forms.

**Comment by KaleabTessera** [comment]
Closing for now, will create new ticket if advanced GA is required.
