### ISSUE TITLE
Add disability list to Create Account form

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#69]
Make the disability question in the create account form a selection box with the following options:

No disabilities
Sight disability
Hearing disability
Communication disability
Physical disability (e.g. difficulty in walking)
Mental disability (e.g. difficulty in remembering or concentrating)
Difficulty in self-care
Other

Also add the following description:
"We use the Washington Group difficulty schemes. This information is collected to ensure that our facilities can accommodate the needs of all attendees."

**Comment by danielamassiceti** [comment]
@KaleabTessera same for this!

**Comment by KaleabTessera** [comment]
Hi @danielamassiceti , thanks for being keen to work on this. I already have a PR out for this and the ethnicity list, **but** you can work on adding better descriptions to the fields if you would like? :)

**Comment by KaleabTessera** [comment]
Closing this. The descriptions can be added as part of https://github.com/deep-learning-indaba/Baobab/issues/62.
