### ISSUE TITLE
Handle blank/null date in Date picker 

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#715]
There are a few bugs with the current [date picker form control](https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/components/form/FormDate.js):
- It displays today's date when the underlying answer is not defined or empty. This makes it confusing to the user who might think that a date is selected, when the underlying model is actually empty/null. 
- If the field is required and the user hasn't chosen a date, they get a validation error "Please fix the errors before continuing." on the page, but there is no visual indicator that the date is required (like other controls have) - this is compounded by the date control displaying today's date.

In order to reproduce this on your local instance, you'll need to add a question with a type of "date" to the existing demo application form. In order to do this, you can browse to the question table in the database in Postico or other DB tool and add a new row with the following values:
- application_form_id: 3
- section_id: 12
- type: date
- description: Enter a date
- order: 1
- headline: Enter a date
- is_required: True
all other fields can be left on their `DEFAULT` value (which will be null) 

Then you can navigate to the application form at http://localhost:8080/test2021/apply and will see a date question on the first page.

**Comment by greeffjean** [comment]
Can this be closed?
