### ISSUE TITLE
Policies

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#72]
Come up with a privacy policy, policy for dealing with complaints about our emails and policy for dealing with bounced emails.

**Comment by nischalhp** [comment]
@avishkar58  I can take this up. Will research on how other communities are dealing with this and come up with a privacy policy.

**Comment by avishkar58** [comment]
Awesome, thanks @nischalhp !

**Comment by nischalhp** [comment]
@avishkar58 - 

With regards to the privacy policy :

1. Are we planning to collect, use and share information? If yes, anything you have on your mind currently?
2. With regards to Links provided in the website, it can involve third party links right?
3. With regards to cookies, are we using them ? If yes, for what purposes are we using the service cookies?
4. What are doing about Data retention?
5. We also have to specify the security measures we have taken? Currently from my understanding its just user based authentication right?
6. We should also mention a legal process in place for processing personal information, in case we do precess personal information. 
7. Address and email id of the organization responsible for running and managing this service. 

Based on this, I can come up with a friendly and simple privacy policy.

**Comment by avishkar58** [comment]
@KaleabTessera @jaderabbit please add any comments you have

**Comment by jaderabbit** [comment]
1. CVs will be shared with sponsors with permission from the user. The information we collect will only be used within the Deep Learning Indaba application and review process

2. Yes, links to 3rd parties could be used

3. Not that I am aware

4. We'd retain the data provided by users for the indaba review process, and we'd retain it into the future in order to analyse past years indaba statistics. @avishkar58 Would we use it to contact indaba members about future events? 

5. User authentication and https

6. I have no idea what this would be referring to. 

7. @avishkar58 Deep Learning Indaba email?

**Comment by avishkar58** [comment]
1. CVs *and email addresses* will be shared with sponsors with permission...
4. Yes we may contact people about future events - people will be able to unsubscribe from these communications
7. info@deeplearningindaba.com

**Comment by nischalhp** [comment]
[PrivacyPolicy.pdf](https://github.com/deep-learning-indaba/Baobab/files/2978222/PrivacyPolicy.pdf)


@avishkar58 @jaderabbit @KaleabTessera  Let me know if this looks good enough for the first draft.

**Comment by jaderabbit** [comment]
@nischalhp Looks great. 

Couple of typos:
```
1. Indaba Review process
2. To analyze past years indaba statistics
3. To contact you for future events. Ofcourse you can opt to unsubscribe from such communications
```
=>
```
1. Indaba Review process
2. To analyse user statistics from prior events
3. To contact you for the Indaba and future events. Of course you can opt to unsubscribe from such communications
```

**Comment by avishkar58** [comment]
Looks good, thanks! 

Few more typos: 
We ensure that all the sensitive information sent to your servers => We ensure that all the sensitive information sent to **our** servers
cannot be and is not guarantedd => cannot be and is not **guaranteed**

Will send to a few more committee members for review as well.

**Comment by KaleabTessera** [comment]
Looks great, just minor changes. Thanks for working on this!

## Minor Changes:
We have access to collect information that you voluntarily provide to us via email, online forms or other direct contact from you, such as your name, email address, home address and telephone number.
-> 
We have access to collect information that you **have** voluntarily **provided** to us via email, online forms or other direct contact ~~from you~~, such as your name, email address, home address and telephone number.

Our services may contain links to other sites. Please be aware that we are not responsible for the content or privacy practises of such other sites. We encourage our users to be aware when they leave our site and to read the privacy statements of any other site that collects personally indentifiable information.
-> 
Our services may contain links to other sites. Please be aware that we are not responsible for the content or privacy **practices** of such other sites. We encourage our users to be aware when they leave our site and to read the privacy statements of any other site that collects personally **identifiable** information.

We retain your data for the following reasons :
1. Indaba Review process
2. To analyze past years indaba statistics
3. To contact you for future events. Ofcourse you can opt to unsubscribe from such communications

->

We retain your data for the following reasons :
1. Indaba Review process **.**
2. To analyze past years **Indaba** statistics **.**
3. To contact you for future events. **Of course** you can opt to unsubscribe from such communications **.**

Please be advised that the security and confidentiality of any communication or material transmitted through the Internet or any wirless network, including via the Services, email or text messages, cannot be and is not guarantedd.
->
Please be advised that the security and confidentiality of any communication or material transmitted through the Internet or any **wireless** network, including via **services**, email or text messages, cannot be and is not **guaranted**.

## Things to consider:
Data Retention:
- Add data retention period.
- Need to confirm we meet the data privacy rules of where our data is stored- currently in the US.

Security:
- Check we are following best practices e.g. time out of the API tokens etc.

**Comment by nischalhp** [comment]
Hello @jaderabbit @avishkar58 @KaleabTessera, 

I have fixed the typos. Please find the updated PDF here. 

@KaleabTessera  - With regards to the things to consider section:

1. Do you already have data retention period?
2. Can add the data privacy rules from the US or a link to it at least.
3. With regards to Security, do we have a configuration for Time out?

@jaderabbit  @avishkar58 your thoughts on the same? 
[PrivacyPolicy.pdf](https://github.com/deep-learning-indaba/Baobab/files/2994001/PrivacyPolicy.pdf)

**Comment by avishkar58** [comment]
Lets add this to the site ASAP, since we're already live and we can always iterate on it more...

**Comment by KaleabTessera** [comment]
Okay cool, @nischalhp We can ignore the 3 things to consider for now and add them later when we are more sure of things, I am happy with the doc.

**Comment by nischalhp** [comment]
Should I just create a PR for the same and submit the doc?

**Comment by avishkar58** [comment]
Yes please! :)
