### ISSUE TITLE
Create basic page and components for Application Form Builder

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#749]
## Background
See the [design doc](https://docs.google.com/document/d/1lFlr-3LuY8cc2zoal9q6qdwnd9NOSN8SAu5ytgm-cuI/edit#)

## Requirements
- Create a new application form builder page 
  - Add a route to it in [EventHome.js](https://github.com/deep-learning-indaba/Baobab/blob/7dcc44b008f4291854079db1e3657ed6a10dfadd/webapp/src/pages/eventHome/EventHome.js#L127) of the form `${match.path}/applicationform` - (this makes it an _event specific route_)
  - Add a link to this route in the Event Admin menu in [App.js](https://github.com/deep-learning-indaba/Baobab/blob/7dcc44b008f4291854079db1e3657ed6a10dfadd/webapp/src/App.js#L120) (it should therefore only be visible to users with the “admin” event role)
- Create components to represent an ApplicationForm, Section and Question
- Add a checkbox to allow the user to select whether the application form accepts nominations or not. To make it clear to the user what this does, the checkbox text should say “Allow candidates to nominate others using this application form” and add a further description saying “Users will be able to submit multiple nominations, including for themselves. If this option is unchecked, a candidate can only apply for themselves”. The value of this checkbox should correspond to the `nominations` field on the application form's JSON representation.
- Query the [event details service](https://github.com/deep-learning-indaba/Baobab/blob/7dcc44b008f4291854079db1e3657ed6a10dfadd/webapp/src/services/events/events.service.js#L14) to get more information about the event (more than what's in the event object passed as a prop to the component) 
  - Display the application form's open and close date, which can be obtained from the `event` object's `application_open` and `application_close` dates
- Maintain a list of Section in the ApplicationForm state
- Maintain a list of Question in the Section state
- Render a card for each Section (add a few of the fields) 
- Render a card for each Question (add a few of the fields) 
- You can use the example JSON below to populate the sections and questions
- Experiment with the UI, making it look decent. 

## Definition of Done
- Code has been developed and tested, following the code style and conventions used by other pages and components
  - Note: any "hard-coded" text in the UI must be added to the two `translation.json` files for [English](https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/public/locales/en/translation.json) and [French](https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/public/locales/fr/translation.json) and accessed using the component's i18n `t` property. This is easier than it sounds, see other pages for an example of how to do it. Use Google Translate to translate English to French
- A test has been created that checks that the page renders
- A PR to merge the changes into develop has been reviewed, comments addressed and merged.

# Example JSON
```
{
  "id": 2,
  "event_id": 2, 
  "is_open": true, 
  "nominations": false, 
  "sections": [
    {
      "name": {
         "en": "Section 1",
         "fr": "Section 1"
      },
      "description": {
         "en": "Description of the section",
         "fr": "Description de la section"
      },
      "order": 1,
      "depends_on_question_id": null,
      "show_for_values": null,
      "key": "candidate_information",
      "questions": [
        {
          "validation_regex": {
             "en": null, 
             "fr": null
          },
          "options": {
              "en": [
                  {"value": "undergrad", "label": "An undergraduate student"}, 
                  {"value": "masters", "label": "A masters student"}, 
                ],
              "fr": [
                  {"value": "undergrad", "label": "un étudiant de premier cycle"}, 
                  {"value": "masters", "label": "un étudiant en maîtrise"}, 
                ],
          },
          "description": {
              "en": null, 
              "fr": null
          },
          "headline": {
              "en": "Question 1", 
              "fr": "Question 1"
          }
          "placeholder": {
              "en": "Select an Option...",
              "fr": "Sélectionnez une option"
          } 
          "is_required": true, 
          "type": "multi-choice", 
          "id": 20, 
          "validation_text": {
              "en": null,
              "fr": null
          } 
          "order": 1,
          "depends_on_question_id": 2,
          "key": null,
          "show_for_values": {
              "en": ["the-matrix", "terminator"],
              "fr": ["the-matrix", "terminator"]
          }
        }
      ], 
 
    }
  ]
}
```

**Comment by Malaba6** [comment]
@avishkar58 is there a way you can provide a mockup or prototype of how you would like this page to look like?

**Comment by avishkar58** [comment]
Hi Eric,

Unfortunately I don't really have time to make a mockup... the idea of this
issue in particular is to create the basic UI that can be iterated on, with
feedback from testers, to ensure that it's intuitive for the end users.
Please take this into consideration when forming your quotation.

Thanks,
Avishkar

**Comment by Malaba6** [comment]
Hi @avishkar58 ,
I would like to request a call with you if you can, since there is a couple of things I would like to get clarified on.
Is that possible?

**Comment by avishkar58** [comment]
Hi Eric,

Yes sure! I could do tomorrow or this weekend if that works for you.

**Comment by Malaba6** [comment]
Tomorrow works for me. Thanks
