### ISSUE TITLE
Create ResponseList page and component

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#779]
### Motivation
As part of the review improvements in Baobab, we want event admins to be able to see a list of responses to their event's application form. Since each application form is unique, they should be able to customise what information from the response appears on this list.

### Dependencies
Depends on the backend APIs created in #774 and #775 but can be implemented using mock data

### Requirements
- Create a new page called ResponseList in webapp/src/pages/responseList
- Add a route to the page in EventHome.js
- Add a menu item pointing to this page under the Event Admin menu in App.js
- Create a new service that talks to the ResponseList API created in #774 (use mock data if that issue hasn't been completed) 
- Create a component to implement the page's functionality
- Add a checkbox labelled "Include un-submitted"
- Add a dropdown list containing questions that the user can select and a "Add to table" button that adds the selected question to the table
  - The list of questions can be obtained by querying the back-end API created in #775
  - Maintain a state of selected `question_ids` (note "add to table" appends to this list) 
- Submit a request to the back-end API on component render, whenever the "Include un-submitted" checkbox changes and whenever a new question is added to the list of selected questions
- The component should render a table containing the details that come back from the API. This table should be sortable by clicking on the column heading
  - See the [InvitedGuest component](https://github.com/deep-learning-indaba/Baobab/blob/d57978b2e55719ea82f2c6e416b5d97994265b5e/webapp/src/pages/invitedGuests/components/InvitedGuestComponent.js#L361) where we use ReactTable
  - Each record in the response from the API will include a list of reviewers, this should be expanded into columns. So, for example, if there are two entries in the reviewers list, there should be 2 columns called "Reviewer 1" and "Reviewer 2" which contain the names of the reviewers (or blank when the entry is null). The length of the list will be the same for all records in a given API response (but note that different events can have different number of reviewers, so you can't hard-code the number of columns!) 
  - Note that the answers corresponding to the selected question_ids will be in a nested list in the response JSON, but should be included as columns in the table
  - Adjust the display of the answer depending on the type:
    - If type is "file" or "multi-file", render links to the files
    - If type is "long-text" display a truncated version of the answer depending on what will fit reasonably in the table. When the user hovers over the cell, it should display the full answer in a tooltip
    - If the type is "multi-choice" or "multi-checkbox", lookup the answer value in the options and render the relevant label
    - See the [AnswerValue](https://github.com/deep-learning-indaba/Baobab/blob/d57978b2e55719ea82f2c6e416b5d97994265b5e/webapp/src/pages/applicationForm/components/ApplicationForm.js#L467) in ApplicationForm.js for inspiration
- Add tests for the functionality

## Example JSON Request to API
```
{
  "event_id": 1,
  "include_unsubmitted": false,
  "question_ids": [3, 5]
}
```

## Example JSON Response from API
```
[
  {
    "response_id": 1,
    "user_title": "Mr",
    "firstname": "Jimmy",
    "lastname": "Fallon",
    "start_date": "2020-06-01 [...]",    // ISO8601 format
    "is_submitted": true,
    "is_withdrawn": false,
    "submitted_date": "2020-06-03 [...]",  // ISO8601 format
    "language": "en",
    "reviewers": [
       {"reviewer_id": 4, "reviewer_name": "Ms Hilary Clinton", "review_response_id": 45},
       {"reviewer_id": 63, "reviewer_name": "Mr Barack Obama", "review_response_id": null},
    ],
    "answers": [
       {"question_id": 3, "value": "Hello world", "type": "short-text", "options": null, "headline": "Question 3"},
       {"question_id": 5, "value": "harry-potter", "multi-choice". "options": [{"label": "Harry Potter", "value": "harry-potter"}, {"label": "X-men", "value": "x-men"}], "headline": "Question 5"}
    ]
  },
  {
    "response_id": 2,
    "user_title": "Ms",
    "firstname": "Halle",
    "lastname": "Berry",
    "start_date": "2020-06-01 [...]",    // ISO8601 format
    "is_submitted": true,
    "is_withdrawn": false,
    "submitted_date": "2020-06-03 [...]",  // ISO8601 format
    "language": "en",
    "reviewers": [
       {"reviewer_id": 63, "reviewer_name": "Mr Barack Obama", "review_response_id": 23},
       null
    ],
    "answers": [
       {"question_id": 3, "value": "Hello world", "type": "short-text", "options": null, "headline": "Question 3"},
       {"question_id": 5, "value": "x-men", "multi-choice". "options": [{"label": "Harry Potter", "value": "harry-potter"}, {"label": "X-men", "value": "x-men"}], "headline": "Question 5"}
    ]
  }
]
```

**Comment by avishkar58** [comment]
Hi @greeffjean - can you get started on this one? Much higher priority than the style changes :) 
Thanks!

**Comment by greeffjean** [comment]
Hi, yes sure thing, right away!

**Comment by greeffjean** [comment]
Have you made payment yet?

**Comment by greeffjean** [comment]
**Create a new service that talks to the ResponseList API created in #774 (use mock data if that issue hasn't been completed)** : This has not been created assuming I am using Mock Data? 

**The list of questions can be obtained by querying the back-end API created in #775**
: Please direct me to an example where this get method is being used, I am not familiar with this particular setup.

Thanks

**Comment by avishkar58** [comment]
Hi Jean,

Yes you can use mock data, as a start you can just return the JSON example from above in a Promise (and add some more examples to test pagination etc) . The API for the question list also hasn't been created yet, so you can also use mock data for that - the example JSON is in #775 

There's lots of examples of services in the [webapp/src/services](https://github.com/deep-learning-indaba/Baobab/tree/develop/webapp/src/services) directory - please create the appropriate services so that when the APIs are created we can just swap your mock promise for the real one.

**Comment by avishkar58** [comment]
Some additional context - some of our applications get a lot of responses, for example, the 2019 Indaba had ~2000 responses, so please keep this in mind when designing the page UX.

**Comment by greeffjean** [comment]
Just a question for now.

When querying the api for questions, will there be a list only of one
question type each or will there be duplicates?

**Comment by avishkar58** [comment]
Hey Jean, there can be multiple questions of the same type, the unique identifier is the `question_id`

**Comment by greeffjean** [comment]
Hi, Please just elaborate a bit more on this, Im finding it a bit vague for
me.

*As part of the review improvements in Baobab, we want event admins to be
able to see a list of responses to their event's application form. Since
each application form is unique, they should be able to customise what
information from the response appears on this list.*

**Comment by greeffjean** [comment]
*The component should render a table containing the details that come back
from the API. This table should be sortable by clicking on the column
heading.  *Please explain how you want me to sort the table?

**Comment by avishkar58** [comment]
Hey Jean,

The first motivation bit is expanded on in the requirements... I just mean that in addition to the standard response fields like the user title, firstname, lastname etc, we also want the users of the page to be able to add columns to the table corresponding to questions from the application form. So for example: if I'm an event admin, I see a table with 10 responses to my event's application form, each row has the name, submitted time etc, but my form also has the question "How old are you" and I want to see this in each row of the table too, so I can select that question from the dropdown and this gets added as an additional column in the table.

The sorting should work like it typically does in a data table - clicking on a column heading sorts the table by that column in ascending order, clicking it again changes it to descending order. This is already supported out the box by ReactTable (https://react-table.tanstack.com/docs/api/useSortBy) (but you may need to provide some custom logic if you change the cell renderer.) See the InvitedGuest example I linked to and run it locally to see how it works.

Hope this makes more sense?

**Comment by avishkar58** [comment]
Hi Jean,
Sorry for the late change, but I realised I forgot a requirement, which is to add the reviewers as columns. I've updated the JSON (you'll see a new "reviewers" field in each object)  and added a description to the requirements:

_("Each record in the response from the API will include a list of reviewers, this should be expanded into columns. So, for example, if there are two entries in the reviewers list, there should be 2 columns called "Reviewer 1" and "Reviewer 2" which contain the names of the reviewers (or blank when the entry is null). The length of the list will be the same for all records in a given API response (but note that different events can have different number of reviewers, so you can't hard-code the number of columns!)")_

**Comment by greeffjean** [comment]
- *Note that the answers corresponding to the selected question_ids will
   be in a nested list in the response JSON, but should be included as columns
   in the table*

*Please just again elaborate here, Im imagining you want every answer to be
in its own row?? *

**Comment by avishkar58** [comment]
No it should be in columns.

For example, if the API gives you back this: (simplified):

```
[
  {
    "response_id": 1,
    "user_title": "Mr",
    "firstname": "Jimmy",
    "lastname": "Fallon",
    "answers" [
         {"question_id": 3, "value": "Hello world", "type": "short-text", "options": null},
         {"question_id": 5, "value": "harry-potter", "multi-choice". "options": [{"label": "Harry Potter", "value": "harry-potter"}, {"label": "X-men", "value": "x-men"}]}  
     ]
  },
  {
    "response_id": 2,
    "user_title": "Ms",
    "firstname": "Halle",
    "lastname": "Berry",
    "answers": [
          {"question_id": 3, "value": "Hello world", "type": "short-text", "options": null},
          {"question_id": 5, "value": "x-men", "multi-choice". "options": [{"label": "Harry Potter", "value": "harry-potter"}, {"label": "X-men", "value": "x-men"}]}
     ]
  }
]
```

Then it should display like this:

| Title | First Name | Last Name | What is your favourite phrase? | What movie did you act in? |
|------|-----------|-------------|-------------------------------|----------------------------|
| Mr     | Jimmy      | Fallon           | Hello world                                 | Harry Potter                          |
| Ms     | Halle        | Berry            | Hello world                                 | X-men                                   |

And the titles "What is your favourite phrase?" and "What movie did you act in?" are the headline you get from the question list, matching on question_id

**Comment by avishkar58** [comment]
Perhaps some of the terminology is causing confusion, so thought I'd clarify:
- A **Response** represents a Users application to a specific Event (confusing because the term response is also overloaded with an "API response"). Each Response should be a row in the table
- A Response contains a set of **Answers**. Each Answer is linked to a **Question** on the Event's Application Form. Since there are lots of Questions in an Application Form, and therefore lots of Answers in a Response, we allow the user of this page to choose a subset of Questions that they want to see the Answers for

**Comment by greeffjean** [comment]
Hi Avishkar.

Just an update: 
Im making good progress with this issue getting quite close completion
