### ISSUE TITLE
Update ResponseList component to support Tags

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#787]
## Motivation
As part of a pre-review or desk-review stage of an event's review process, responses may be grouped into categories. We will create a fairly generic tagging mechanism to support this categorisation (a response may have 0 or more tags associated with it). This issue adds functionality to the ResponseList component so that the event admin can see the tags associated with each response and can also filter responses using these tags.

## Dependencies
Depends on the ResponseList component created in #779 
Depends on adding tags to the ResponseList API in #784, but can be done using mock data if the back-end work hasn't been done yet
Depends on the TagList API created in #778 but can be done using mock data if the back-end work hasn't been done yet

## Requirements
- Update the ResponseList service created in #779 to accept a list of tag IDs (for example `[1, 3, 5]`) that gets passed to the API get method as a `tags` parameter
- Add a dropdown list of tags which are obtained from the TagList API (create a service to talk to this API, see the example JSON below for the format you can expect to receive data from this API)
- Maintain a list of filter tags in the component state and display this list on the UI (show each tag in the list as a "pill")
- When the user selects a tag from the dropdown, it should be added to the list of filter tags and the dropdown should "reset" (ie reset the value to null/blank)
- When the user adds a tag to the filter list, re-query the ResponseList service to retrieve the responses matching the updated list of filter tags
- For each filter tag displayed as a pill, add a "trash" icon that the user can use to remove the tag from the set of filters, this should also trigger a re-querying of the Responses
- Add a new column to the table to display the list of tags associated with each response, display these tags as "pills", sort the tags alphabetically

### Example JSON from TagList API
```
[
  {"id": 5, "event_id": 3, "name": "First Tag"},
  {"id": 6, "event_id": 3, "name": "Second Tag"},
  {"id": 7, "event_id": 3, "name": "Third Tag"}
]
```

### Example JSON from ResponseList API
Note this is mostly the same as before, but there is a new "tags" field on each response in the list

```
[
  {
    "response_id": 1,
    "user_title": "Mr",
    "firstname": "Jimmy",
    "lastname": "Fallon",
    "start_date": "2020-06-01 [...]",    // ISO8601 format
    "is_submitted": true,
    "is_withdrawn": false,
    "submitted_date": "2020-06-03 [...]",  // ISO8601 format
    "language": "en",
    "answers": [
       {"question_id": 3, "value": "Hello world", "type": "short-text", "options": null},
       {"question_id": 5, "value": "harry-potter", "multi-choice". "options": [{"label": "Harry Potter", "value": "harry-potter"}, {"label": "X-men", "value": "x-men"}]},
     "tags": [         //  <-------- NEW
          {"id": 5, "name": "Education"},
          {"id": 7, "name": "Healthcare"}
      ]
    ]
  },
  {
    "response_id": 2,
    "user_title": "Ms",
    "firstname": "Halle",
    "lastname": "Berry",
    "start_date": "2020-06-01 [...]",    // ISO8601 format
    "is_submitted": true,
    "is_withdrawn": false,
    "submitted_date": "2020-06-03 [...]",  // ISO8601 format
    "language": "en",
    "answers": [
       {"question_id": 3, "value": "Hello world", "type": "short-text", "options": null},
       {"question_id": 5, "value": "x-men", "multi-choice". "options": [{"label": "Harry Potter", "value": "harry-potter"}, {"label": "X-men", "value": "x-men"}]},
      "tags": [             //  <-------- NEW
          {"id": 2, "name": "Desk Reject"},
          {"id": 7, "name": "Healthcare"}
      ]
    ]
  }
]
```

**Comment by greeffjean** [comment]
Please review `Example JSON from ResponseList API` above and correct the error where the new entry is, the new entry needs to be wrapped in curly braces, Im not sure where exactly you want to place the new object key, it would be easier if it was not in the answers key, Im not sure if this is pre determined  already..

**Comment by avishkar58** [comment]
Hi Jean, thanks for pointing that out - it was a mistake, the tags should not be inside the answers. I've updated the JSON now.
