### ISSUE TITLE
Add ability to add tags on response detail page

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#798]
## Motivation
Tags allow event admins and reviewers to group applications in a generic way. We want event admins to have the ability to add tags to a response on the response detail page. 

## Dependencies
Depends on the response detail page created in #781 and the tag list added to it in #797 
For the back-end, depends on the TagAPI and TagListAPI created in #778 and the ResponseTag API created in #786, but this issue can be done using dummy data if those haven't been completed yet. 

## Requirements
Update the Response detail page with the following:
- Add a button saying "+ Add Tag" to the right of the list of tags
  - Clicking on the button should open a dropdown list with a list of tags. The list of tags can be retrieved from the TagList API, see an example JSON response from this API below
  - Selecting a tag from the list should send a POST request to the ResponseTag API to add the tag to the Response. If the response from the API is a 201 (created), add the tag to the list of tags. If it is an error, display this to the user.
- Allow the user to create a new tag by adding a "New Tag" button to the dropdown list of tags. 
  - Clicking on the new tag button opens a dialog that prompts the user for a name in each language supported by the event)
    - You can determine which languages the event supports by calling the getEvent function in [events.service.js](https://github.com/deep-learning-indaba/Baobab/blob/4a530ebb3777b4f9c6460bf7dab1bbce9b5adefd/webapp/src/services/events/events.service.js#L14) and look at which keys exist in the returned `event.name` property (for example, it might be "en" and "fr" or just "en") 
  - The user can Save or Cancel, Save sends a POST request to the TagAPI (see example JSON below) to create the new tag. If it was successful, then send a request to the ResponseTag API as above to add the new tag to the response. If there is an error, display it to the user.
- Allow the user to remove a tag by adding a cross/trash icon on each of the tag pills
  - Clicking on this icon should prompt the user if they're sure they want to remove the tag 
  - If the user confirms yes, then send a DELETE request to the ResponseTag API, if the response is success (200) remove the tag from the list, if there is an error, display this to the user. See below for the JSON format of the DELETE request.

### Example of response from calling GET on the TagList API
This is used to retrieve the list of available tags
```
[
  {"id": 5, "event_id": 3, "name": "First Tag"},
  {"id": 6, "event_id": 3, "name": "Second Tag"},
  {"id": 7, "event_id": 3, "name": "Third Tag"}
]
```

### Example of POST request to ResponseTag API
This is used to add a tag to the current response being viewed
```
{
  "tag_id": 5,   // This corresponds to the id property of the tag obtained from the TagList API
  "response_id": 2,   // This corresponds to the response that is currently being viewed (from the URL parameter) 
  "event_id": 1   // This comes from this.props.event.id
}
```

### Example of DELETE request to the ResponseTag API
This is used to remove a tag from a response
```
{
    'tag_id': 5,  
    'response_id': 2,
    'event_id': 1
}
```

### Example of POST request to TagAPI
This is used to create a new tag along with the translations in all languages supported by the event
```
{
  "event_id": 3,
  "name": {
     "en": "Nice Tag",
     "fr": "Belle étiquette"
  }
}
```

**Comment by greeffjean** [comment]
Hi Avishkar, making good headway here just a couple of questions: 

1. The ResponseTag API does not appear to exist, how would you like me to proceed? 

> Selecting a tag from the list should send a POST request to the ResponseTag API to add the tag to the response. If the response from the API is a 201 (created), add the tag to the list of tags. If it is an error, display this to the user.

2. I am being Signed Out from the App when I try to run the `getEvent API function` in event.service.js , please see terminal response: 

> xhr.js:155 GET http://localhost:5000/api/v1/event?id=undefined&cache_bust=1&language=en 401 (UNAUTHORIZED)

**Comment by avishkar58** [comment]
Hi Jean,

1. Correct, it doesn't exist yet, so please make a service with a dummy implementation - so for now you can just construct the JSON request in the correct format and return a hard-coded status of 201 for now. The page is showing a Response, and the tag should be added to the Response that is currently being shown on the page, which is identified by the ID that's in the URL (`this.props.match.params.id`) (in hindsight I wish I chose a different name for "Response" to avoid the confusion with the double meaning of "Response" referring to the set of answers, which is what I mean here, and not an HTTP response) 

2. Ah looks like there's a bug in the service that it's not passing the authentication header, please modify line 16 of events.service.js to this:
`.get(baseUrl + `/api/v1/event?id=` + event_id + "&cache_bust=1", { headers: authHeader() })`

**Comment by avishkar58** [comment]
I just realised I forgot to add the deletion feature - please see the updated description
