### ISSUE TITLE
Add logic to section and question fields

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#850]
## Background
See the [design doc](https://docs.google.com/document/d/1lFlr-3LuY8cc2zoal9q6qdwnd9NOSN8SAu5ytgm-cuI/edit#)

## Dependencies
Depends on the fields created in #849 

## Requirements
Add the following logic to the section and question fields on the application form builder.

#### `show_for_values`
If the question referred to in `depends_on_question_id` has type "multi-choice":
Allow the user to select one or more of the options from the dependency question. (For example, if the user selects the question "What is your favourite movie" in the `depends_on_question_id` field, this field should display the list of the options that the "What is your favourite movie" question has. The user should be able to check some of these options, for example "The Matrix", "Terminator". The final value for the field is a JSON array of these values, for example `["The Matrix", "Terminator"]`). See below the description of options below and make sure that the values are used in the field value and the labels are used in the display.

If the question referred to in `depends_on_question_id` has type "single-choice":
The user can select "True" or "False" and this becomes the value of the field. 

#### `show_for_values`
This logic is the same as described in the Section above

#### `validation_regex`
The majority of users will not be able to write regex themselves, so the UI should make it easy to enter the most common type of regex validation rule, *word limits*. By default, the validation rule should be presented to the user in the form of a minimum (MIN) and maximum (MAX) word limit input box ("friendly mode"). Either minimum or maximum can be blank. They should be translated into the following regex:
`^\s*(\S+(\s+|$)){MIN,MAX}$`  (if the minimum is blank, set MIN to 0, if the maximum is blank, leave out MAX). If both the minimum and maximum are blank, the validation_regex should be set to null. 

Add an advanced checkbox which removes the minimum and maximum inputs and allows the user to edit the regex directly. 

One complication here is that when editing an existing application form, if the regex is of the form `^\s*(\S+(\s+|$)){MIN,MAX}$` (or null) then the MIN and MAX should be extracted and displayed in the friendly format. If the validation_regex does not match this form, it should be displayed in "advanced mode" 

#### `validation_text`
This depends on the value of the `validation_regex` field. If the validation for this question is in "advanced mode", simply display an input box that allows the user to edit this field directly. If the validation is in "friendly mode", the validation_text property should also be set to “You must enter {MIN} to {MAX} words” if the minimum and maximum are greater than 0. If the minimum is 0 (assume blank is 0), the validation_text property should be set to “You may enter no more than {MAX}” words. If the maximum is blank but the minimum is greater than 0, the validation_text should be “You must enter at least {MIN} words”. If both the minimum and maximum are blank, the validation_text should be blank. 
**TODO**: What about populating the other languages besides English? Can we use the Google Translate API to do this?

#### `options`
If the question's `type` is "multi-choice" or "multi-checkbox":
Allow the user to enter a list of "value and "label" pairs (using input boxes for value and label, a plus button to add a new row and trash icon to remove a row). The list of value and label pairs should be translated into a JSON representation that looks like the example below to store in the `options` field:
```
[
  {"value": "undergrad", "label": "An undergraduate student"}, 
  {"value": "masters", "label": "A masters student"}, 
  {"value": "industry", "label": "Industry Professional"},
]
```
In this case, at least one option in the list is **required**.
(Remember when editing an existing form, the JSON representation should also be mapped to this UI list)
(Remember this is translatable, so this should be replicated for each language)

If the question's type is "reference", prompt the user for a minimum and maximum number of referrals and translate this to/from the following JSON example to store in the options field:
`{"max_num_referral": 3, "min_num_referral": 1}`
In this case, the options is **required**

If the question type is "file" or "multi-file", prompt the user for a list of file extensions and map this to/from a JSON representation that looks like this example:
`{"accept": [".csv", ".xls", ".xlsx"]}`
In this case, the options are not required.

### Deleting a question
If the user deletes a question and the question is referred to as a dependency of another question or section (eg if the user deletes question ID 10 and the `depends_on_question_id` property of one or more other sections or questions contains the value 10), add a note to the confirmation modal dialog that the question is a dependency of other sections/questions. If the user confirms the deletion, remove the deleted ID from any `depends_on_question_id` properties.

**Comment by NikolaSiplakova** [comment]
Hi, I'd like to work on one of your issues.I tried to sign up to get access to your page, but I haven't recieved confirmation email yet. Could you help me?
