### ISSUE TITLE
Application Form Builder Integration

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#851]
## Background
See the [design doc](https://docs.google.com/document/d/1lFlr-3LuY8cc2zoal9q6qdwnd9NOSN8SAu5ytgm-cuI/edit#)

## Dependencies
Depends on #847 and #850

## Requirements
This issue involves tying up any loose ends remaining after the previous issues have been completed and ensuring that the front-end works correctly with the backend. 

- Create methods in [applicationForm.service.js](https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/services/applicationForm/applicationForm.service.js) to interact with the GET, POST and PUT methods of the `applicationformdetail` backend API
  - The GET method will retrieve an existing application form represented similarly to the example JSON below. It will return null if there is no application form for the event (in which case the front-end should be in "new" mode)
  - The POST and PUT methods will accept a JSON representation of an application form similar to the JSON below, note that for the POST method, none of the ids will be populated. For the PUT method, the ids of the application form itself and any existing sections/questions that need to be updated should be populated, and the ids of new sections/questions should be excluded.
- When the main component mounts, query the service's GET method to determine whether there is already an application form for the event. If there is an application form, the page should enter "edit" mode, the sections and questions and their respective fields should be populated and allow the user to edit these. If there is no application form, the page should enter "new" mode and allow the user to create a new application form from scratch. 
- Add a Save button to the Application Form builder page created in previous issue.
  - If this is a new application form, call the appropriate service method to send a POST request to the backend
  - If the user was editing an existing application form, call the appropriate service method to send a PUT request to the backend.
- After saving the application form, redirect the user to the event home page.

# Example JSON
```
{
  "id": 2,
  "event_id": 2, 
  "is_open": true, 
  "nominations": false, 
  "sections": [
    {
      "name": {
         "en": "Section 1",
         "fr": "Section 1"
      },
      "description": {
         "en": "Description of the section",
         "fr": "Description de la section"
      },
      "order": 1,
      "depends_on_question_id": null,
      "show_for_values": null,
      "key": "candidate_information",
      "questions": [
        {
          "validation_regex": {
             "en": null, 
             "fr": null
          },
          "options": {
              "en": [
                  {"value": "undergrad", "label": "An undergraduate student"}, 
                  {"value": "masters", "label": "A masters student"}, 
                ],
              "fr": [
                  {"value": "undergrad", "label": "un étudiant de premier cycle"}, 
                  {"value": "masters", "label": "un étudiant en maîtrise"}, 
                ],
          },
          "description": {
              "en": null, 
              "fr": null
          },
          "headline": {
              "en": "Question 1", 
              "fr": "Question 1"
          }
          "placeholder": {
              "en": "Select an Option...",
              "fr": "Sélectionnez une option"
          } 
          "is_required": true, 
          "type": "multi-choice", 
          "id": 20, 
          "validation_text": {
              "en": null,
              "fr": null
          } 
          "order": 1,
          "depends_on_question_id": 2,
          "key": null,
          "show_for_values": {
              "en": ["the-matrix", "terminator"],
              "fr": ["the-matrix", "terminator"]
          }
        }
      ], 
 
    }
  ]
}
```

**Comment by NikolaSiplakova** [comment]
Hi, I have a problem with signing in. I have signed up at https://test-baobab.deeplearningindaba.com/, I got verification email, but my new account doesn't work on localhost. Could you help me?

**Comment by avishkar58** [comment]
Hi @NikolaSiplakova 
All the instances are separate, so if you want to use your local app running on localhost you need to sign up on https://locahost:8080/createAccount . Do note however that in debug mode the app doesn't send emails, but instead logs them to the terminal, so in order to get your verification link, just keep an eye on your terminal where the docker containers are running and you'll see the email there.

Alternatively, after creating an account locally, you can open up the app_user table in the database (which will be running on localhost, port 5432, with username and password both "docker" and the database name also "docker") and update the verified column to True

**Comment by avishkar58** [comment]
Hi @Malaba6 ,

I've updated the backend for this now, you can find the endpoint at /api/v1/application-form-detail which supports GET, POST and PUSH. The code is [here](https://github.com/deep-learning-indaba/Baobab/blob/608ed379b6bfe06f6ba45af52aa2257451047b5c/api/app/applicationModel/api.py#L134) if you're interested. 

The JSON format it accepts is pretty much the same as the example above, however as you also noticed, we do need some kind of surrogate IDs for the questions to refer to in the depends_on_question_id field. So for this reason the backend now expects that *new* questions have a `surrogate_id` field and *existing* questions that are being updated have an `id` field (a question should only have one of these fields, not both). Also, the `surrogate_ids` can be any number, but should not overlap with the Ids - so for a new form you can start them at 1, for an existing form that's being edited, you can start them at max(all question ids) + 1. The `depends_on_question_id` will then refer to either the `surrogate_id` or the `id`. Hope this makes sense!

**Comment by Malaba6** [comment]
> Hi @Malaba6 ,
> 
> I've updated the backend for this now, you can find the endpoint at /api/v1/application-form-detail which supports GET, POST and PUSH. The code is [here](https://github.com/deep-learning-indaba/Baobab/blob/608ed379b6bfe06f6ba45af52aa2257451047b5c/api/app/applicationModel/api.py#L134) if you're interested.
> 
> The JSON format it accepts is pretty much the same as the example above, however as you also noticed, we do need some kind of surrogate IDs for the questions to refer to in the depends_on_question_id field. So for this reason the backend now expects that _new_ questions have a `surrogate_id` field and _existing_ questions that are being updated have an `id` field (a question should only have one of these fields, not both). Also, the `surrogate_ids` can be any number, but should not overlap with the Ids - so for a new form you can start them at 1, for an existing form that's being edited, you can start them at max(all question ids) + 1. The `depends_on_question_id` will then refer to either the `surrogate_id` or the `id`. Hope this makes sense!

Cool! looking into it
