### ISSUE TITLE
Fix failing integration test

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#852]
Fix the following two integration tests in [signup.spec.js](https://github.com/deep-learning-indaba/Baobab/blob/develop/integration-tests/cypress/integration/signup.spec.js) - it seems to be an issue with the test because the actual signup page is working fine. 
- Signup form cannot be submitted in if you havent accepted the policy or if you are underage.
- Singup form can be submitted if you fill in everything correctly.

**Comment by avishkar58** [comment]
Good for any newcomers with some Cypress experience or wanting to learn about Cypress

**Comment by avishkar58** [comment]
Hi @gausam - I'm going to design some new features this weekend and create issues for you to work on next week, but if I don't get to it in time, please look into fixing this test in the meantime.

**Comment by gausam** [comment]
Sounds good to me. Thanks, Avishkar 🙂

**Comment by gausam** [comment]
Sounds good to me. Thanks, @avishkar58 🙂

**Comment by avishkar58** [comment]
Hi @gausam how are things going with this issue?
