### ISSUE TITLE
Add Review Summary to Review Detail Page

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#877]
## Background
Each response to an application form can be reviewed by multiple reviewers. These reviewers answer a configurable set of questions about the response and assign appropriate scores and/or provide comments on the response. The scores and comments submitted by a reviewer is a called a "review response". 

The administrator of the event is interested in viewing reviews in the form of a summary at the application response level, where the scores are an average of the scores assigned by the review responses. 

## Requirements
- Update the review details page created in #865 to add a "Detail" and "Summary" button/tab
- The page should open by default in "Detail" mode, displaying the current table.
- When the user clicks on the "Summary" button/tab, the page should query a review response summary API (to be created, see the example JSON below) to get a summary of the review responses (one per response_id) 
- The summary should be displayed in a table very similar to the review response detail table
  - Don't display the "review_response_id" as a column
  - The value in each row of the response_id column should be a clickable link which takes the user to the associated response detail page (which will be at /{eventKey}/responsePage/{responseId})
  - The "response_user_*" columns should be concatenated into a "Candidate" column
  - Each "review response" contains some nested fields called "identifiers". These should be pivotted and displayed as columns in the table, using the "headline" as the column heading and the "value" as the cell value. The number of identifiers and scores and the associated headlines will all differ per event (so these columns can't be hard-coded!).
  - Each "review response" also contains some nested fields called "scores". These should also be pivotted and displayed as columns in the table. The "headline" and "description" forming the column heading and the "score" forming the cell value
  - The "Total" column should be the last column in the table

- Just like the Detail tab, there should be an "Export to CSV" button which exports the contents of the table to a CSV.

### Key differences between the detail and summary data
- The summary data will contain only one entry per response_id
- The summary data does not contain "Reviewer" details (because it aggregates over all reviewers) 
- The summary will contain a **subset** of the scores available in the details, because the API will only return numerical scores

- Ideally most of the code written for the response detail should be re-used, pointing it at a different data source.

## Example JSON
```
[
  {  
    "response_id": 3,
    "response_user_title": "Ms",
    "response_user_firstname": "Jane",
    "response_user_lastname": "Bloggs",
    "identifiers": [    
        {
            "headline": "Organisation",     // From question_translation
            "value": "Pets R Us"                // From answer
        },
        {
            "headline": "Country",
            "value": "Nigeria"
        },
    ],
    "scores": [
        {
            "headline": "Ethical Considerations",   // From review_question_translation
            "description": "How ethical is the candidate's proposal from 1 to 5?",   // From review_question_translation
            "type": "short-text",   // From review_question
            "score": 4,   // From review_score
            "weight": 1    // From review_question
        },
        {
            "headline": null,
            "description": "What is your overall rating?",
            "type": "multi-choice",
            "score": 5,
            "weight": 2
        }
    ],
    "total": 12
  },

  {  
    "response_id": 4,
    "response_user_title": "Dr",
    "response_user_firstname": "Alex",
    "response_user_lastname": "Person",
    "identifiers": [    
        {
            "headline": "Organisation",     
            "value": "Nokia"                
        },
        {
            "headline": "Country",
            "value": "South Africa"
        },
    ],
    "scores": [
        {
            "headline": "Ethical Considerations",   // From review_question_translation
            "description": "How ethical is the candidate's proposal from 1 to 5?",   // From review_question_translation
            "type": "short-text",   // From review_question
            "score": 3,   // From review_score
            "weight": 1    // From review_question
        },
        {
            "headline": null,
            "description": "What is your overall rating?",
            "type": "multi-choice",
            "score": 3,
            "weight": 2
        }
    ]
    "total": 11
  },
]
```

The example JSON above should result in a table with 7 columns and 2 rows. The columns would be:
| Response ID | Candidate | Organisation | Country | Ethical Considerations; How ethical is the candidate's proposal from 1 to 5? | What is your overall rating? | Total |

**Comment by avishkar58** [comment]
Hi @gausam - here is the next issue for you please, this should be a simple extension to the review detail page you just worked on. Thanks!

**Comment by gausam** [comment]
@avishkar58 Thanks Avishkar. I'll start on this tomorrow.
