### ISSUE TITLE
Create a ReviewResponseSummaryList API

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#878]
Create a new ReviewResponse**Summary**List API in reviews/api.py
This is very similar to the ReviewResponse**Detail**List with the key difference that the summary version _groups by response_ and _aggregates the numerical scores_.

In particular, the API should: 
- Accept event_id (int) and language (str) parameters
- Ensure that the logged in user is an event admin for the event
- Query the database for all review responses associated with the given event using a new method on the review repository, as well as some details about the response, the applicant and the reviewer. These details include:
  - The user who submitted the response (called "response_user" in the JSON below)
  - Questions with a key of "review-identifier" and the corresponding Answers from the response
  - The review questions and review scores associated with the review response
- Group the review responses by response_id, drop any scores that are not numerical and aggregate the values
- Compute a **total** which is the weighted average of the numerical scores (weighted by the `weight` value found on review_question)

## Example JSON response
Notes:
- response_identifiers are the headlines (translated) and answers to all questions from the relevant application form that have a key value of "review-identifier"
- The scores should be filtered to questions of type "multi-choice", "long-text" and "short-text"

```
[
  {  
    "response_id": 3,
    "response_user_title": "Ms",
    "response_user_firstname": "Jane",
    "response_user_lastname": "Bloggs",
    "identifiers": [    
        {
            "headline": "Organisation",     // From question_translation
            "value": "Pets R Us"                // From answer
        },
        {
            "headline": "Country",
            "value": "Nigeria"
        },
    ],
    "scores": [
        {
            "headline": "Ethical Considerations",   // From review_question_translation
            "description": "How ethical is the candidate's proposal from 1 to 5?",   // From review_question_translation
            "type": "short-text",   // From review_question
            "score": 4,   // An **average** of the values of review_score
            "weight": 1    // From review_question
        },
        {
            "headline": null,
            "description": "What is your overall rating?",
            "type": "multi-choice",
            "score": 5,
            "weight": 2
        }
    ],
    "total": 12
  },

  {  
    "response_id": 4,
    "response_user_title": "Dr",
    "response_user_firstname": "Alex",
    "response_user_lastname": "Person",
    "identifiers": [    
        {
            "headline": "Organisation",     
            "value": "Nokia"                
        },
        {
            "headline": "Country",
            "value": "South Africa"
        },
    ],
    "scores": [
        {
            "headline": "Ethical Considerations",   // From review_question_translation
            "description": "How ethical is the candidate's proposal from 1 to 5?",   // From review_question_translation
            "type": "short-text",   // From review_question
            "score": 3,   // An **average** of the values of review_score
            "weight": 1    // From review_question
        },
        {
            "headline": null,
            "description": "What is your overall rating?",
            "type": "multi-choice",
            "score": 3,
            "weight": 2
        }
    ]
    "total": 11
  },
]
```

**Comment by amritpurshotam** [comment]
@avishkar58 

1. Should we not rather filter the review questions where `weight > 0`? I'm doing some testing now and on the `long-text` questions these just become `0` which isn't really informative. Or am I missing a case where a `long-text` can be cast to a numeric value (and the weight will also be > 0)? Getting something like the below currently

```
{
    'response_id': 2,
    'response_user_title': 'Dr',
    'response_user_firstname': 'Alex',
    'response_user_lastname': 'Person',
    'identifiers': [{
            'headline': 'Organisation',
            'value': 'Nokia'
        }, {
            'headline': 'Country',
            'value': 'South Africa'
        }
    ],
    'scores': [{
            'headline': 'Ethical Considerations',
            'description': "How ethical is the candidate's proposal from 1 to 5?",
            'type': 'short-text',
            'score': 2.5,
            'weight': 1.0
        }, {
            'headline': None,
            'description': 'Comments for the candidate',
            'type': 'long-text',
            'score': 0.0,
            'weight': 0.0
        }, {
            'headline': None,
            'description': 'What is your overall rating?',
            'type': 'multi-choice',
            'score': 1.5,
            'weight': 2.0
        }
    ],
    'total': 5.5
}
```

2. Should the totals in your example actually be 14 (4x1 + 5x2) and 9 (3x1 + 3x2)? And will then actually be the weighted *sum* of the average scores which seems to make the most sense and how I've implemented it now. Just want to make sure I haven't missed anything in your example.

**Comment by avishkar58** [comment]
Hi @amritpurshotam yes your suggestion to filter on weight > 0 makes sense and you're quite right about the totals! Don't know what went wrong with my maths there :D
